configs/det/det_mv3_east.yml
configs/det/det_r50_vd_db.yml
configs/det/det_r50_vd_east.yml
doc/detection.md
doc/installation.md
tools/program.py

* fix doc typo
* save weights at epoch when save_epoch_step=1

Save weights at epoch 0

---

doc/recognition.md
tools/export_model.py

fix use_gpu=False

---

ppocr/data/det/dataset_traversal.py
ppocr/data/reader_main.py
ppocr/data/rec/dataset_traversal.py
ppocr/utils/character.py

Adaptive Windows

---

doc/installation.md
tools/infer/utility.py

- opt visualized function
- supplement docker instructions on cpu

opt visualized func and add docker usage in cpu

---

ppocr/data/det/db_process.py
tools/infer/utility.py

fix bug in visualization
bugs：
- Nan score
- unnormal blank image in txt visualization

fix bug in results visualization

---

configs/rec/rec_chinese_common_train.yml

upload common ch rec yml file

---

README.md
README_en.md

It seems like I've been messing up. Both README are in Chinese. This version fixes that.

English translated docs version 09.06.20.01 

---

README.md
README_en.md
doc/doc_ch/detection.md
doc/doc_ch/inference.md
doc/doc_en/detection_en.md
doc/doc_en/inference_en.md
ppocr/data/rec/img_tools.py

- 添加contributor
- 添加断点训练的说明，区分checkpoints和pretrain_weights
- 添加自定义字典在运行inference  model时需要指定rec_char_dict_path参数
- 针对识别数据不符合格式 加了 提示信息

optimize doc and error message

---

tools/program.py

fix: Variable [ tmp_4 ] Not found, Please make sure run startup program

fix can not find tmp_4

---

ppocr/data/det/dataset_traversal.py

fix https://github.com/PaddlePaddle/PaddleOCR/issues/228

fix img shape not match when concat

---

doc/doc_ch/recognition.md
doc/doc_en/recognition_en.md
ppocr/modeling/architectures/__init__.py
ppocr/modeling/backbones/__init__.py
ppocr/modeling/heads/__init__.py
ppocr/modeling/losses/__init__.py
ppocr/modeling/stns/__init__.py
tools/eval_utils/eval_det_utils.py
tools/eval_utils/eval_rec_utils.py

1. Add `__init__` and Fix some comments to support py2.
2. Fix typo(paddle_det->paddle_cor)

fix ch comment to support py2 and some other typo

---

tools/infer/predict_rec.py
tools/infer_rec.py
tools/train.py

- fix Nan results 
- add test_reader for debug reader

fix Nan results and add test_reader func

---

deploy/lite/readme.md

update docs for deploying ocr demo with Paddle Lite

update docs for deploying ocr demo with Paddle Lite

---

deploy/cpp_infer/src/ocr_det.cpp
deploy/cpp_infer/src/ocr_rec.cpp
deploy/cpp_infer/src/postprocess_op.cpp

1. disable config info for cpp infer 
2. fix assert error for opencv

disable config info for cpp infer

---

deploy/cpp_infer/include/ocr_rec.h

Support to recognize space text

---

ppocr/optimizer.py

add l2 decay interface

---

deploy/lite/db_post_process.cc

-  fix https://github.com/PaddlePaddle/PaddleOCR/issues/353

fix cv Exception

---

deploy/cpp_infer/src/postprocess_op.cpp
ppocr/modeling/backbones/rec_mobilenet_v3.py
tools/eval.py
tools/eval_utils/eval_rec_utils.py
tools/infer_det.py
tools/infer_rec.py
tools/test_hubserving.py
tools/train.py

Fix eval comment and backbone stride

---

doc/doc_ch/inference.md
doc/doc_en/inference_en.md
doc/doc_en/recognition_en.md

Synchronize English documents with Chinese documents

sync en doc

---

deploy/cpp_infer/CMakeLists.txt
deploy/cpp_infer/docs/windows_vs2019_build.md
deploy/cpp_infer/readme.md
deploy/cpp_infer/src/config.cpp
deploy/cpp_infer/src/utility.cpp
deploy/cpp_infer/tools/build.sh
deploy/cpp_infer/tools/config.txt

add cpp inference for windows

---

deploy/pdserving/det_local_server.py
deploy/pdserving/det_web_server.py
deploy/pdserving/ocr_local_server.py
deploy/pdserving/ocr_web_client.py
deploy/pdserving/ocr_web_server.py
deploy/pdserving/readme.md
deploy/pdserving/rec_local_server.py
deploy/pdserving/rec_web_server.py

增加Paddle Serving的文档和代码。
包括 det+rec， det， rec的模式。

Add OCR Serving

---

deploy/pdserving/readme.md

目前paddle_serving_server_gpu和paddle_serving_app属于测试环节，
先提供beta版本给用户 从百度云下载

OCR Padle Serving readme 改动

---

deploy/pdserving/readme.md

Update paddle serving readme.md support py3

---

doc/doc_ch/serving.md
doc/doc_en/serving_en.md

Add windows doc.
Solve the bug for #418  and #392

fix hub serving doc

---

tools/infer/predict_det.py

See title(Images can not be saved if the dir does not exist).

fix save img for pred_det

---

ppocr/utils/utility.py

fix image list postfix

---

ppocr/data/det/db_process.py
ppocr/utils/utility.py
tools/infer/predict_det.py
tools/infer/predict_rec.py
tools/infer/predict_system.py

- read gif read func
- remove det_box_final

read gif read func

---

README.md
README_cn.md
ppocr/data/det/dataset_traversal.py
ppocr/data/rec/dataset_traversal.py

add beyond into thanks

---

doc/doc_ch/config.md
doc/doc_en/config_en.md
ppocr/data/rec/img_tools.py
ppocr/optimizer.py

add piecewise decay

---

ppocr/data/rec/dataset_traversal.py

add error message

---

deploy/android_demo/app/build.gradle
deploy/android_demo/app/src/main/AndroidManifest.xml
deploy/android_demo/app/src/main/cpp/native.cpp
deploy/android_demo/app/src/main/cpp/ocr_ppredictor.cpp
deploy/android_demo/app/src/main/cpp/ocr_ppredictor.h
deploy/android_demo/app/src/main/cpp/ppredictor.h
deploy/android_demo/app/src/main/cpp/predictor_output.h
deploy/android_demo/app/src/main/java/com/baidu/paddle/lite/demo/ocr/AppCompatPreferenceActivity.java
deploy/android_demo/app/src/main/java/com/baidu/paddle/lite/demo/ocr/MainActivity.java
deploy/android_demo/app/src/main/java/com/baidu/paddle/lite/demo/ocr/MiniActivity.java
deploy/android_demo/app/src/main/java/com/baidu/paddle/lite/demo/ocr/Predictor.java
deploy/android_demo/app/src/main/java/com/baidu/paddle/lite/demo/ocr/SettingsActivity.java
deploy/android_demo/app/src/main/res/layout/activity_main.xml
deploy/android_demo/app/src/main/res/layout/activity_mini.xml

1. add Mini Demo
2. upgrade UI
3. modify comment as English

mini demo modification

---

deploy/pdserving/det_local_server.py
deploy/pdserving/det_web_server.py
deploy/pdserving/ocr_local_server.py
deploy/pdserving/ocr_web_server.py
deploy/pdserving/readme.md
deploy/pdserving/rec_web_server.py

本PR做以下更新
1. 增加CPU的支持（尽快正式发版）
2. 修改python文件以同时支持GPU/CPU

pdserving deploy增加CPU支持

---

ppocr/data/rec/dataset_traversal.py
ppocr/modeling/backbones/rec_mobilenet_v3.py
ppocr/modeling/heads/rec_ctc_head.py
ppocr/utils/save_load.py

add stride config of backbone and fix load ckp

---

deploy/pdserving/det_local_server.py
deploy/pdserving/ocr_local_server.py
deploy/pdserving/readme.md
deploy/pdserving/rec_local_server.py

pdserving add convert to serving model

---

deploy/cpp_infer/include/config.h

fix cpp infer

---

ppocr/data/rec/dataset_traversal.py
ppocr/modeling/heads/self_attention/model.py

format code

---

deploy/cpp_infer/src/ocr_det.cpp
deploy/cpp_infer/src/ocr_rec.cpp
deploy/cpp_infer/tools/config.txt
tools/infer/predict_system.py
tools/infer/utility.py

fix mklnn memory leak

---

deploy/pdserving/readme.md

Serving 0.3.2 正式版已经Release并通过验证
修改`deploy/pdserving/readme.md`
1. 删除beta相关提示，删除wget whl链接
2. 换正式版安装方式

Update readme.md cuz Serving 0.3.2 release

---

doc/doc_ch/installation.md
doc/doc_en/installation_en.md

fix docker link

---

deploy/cpp_infer/readme.md
deploy/cpp_infer/readme_en.md
deploy/cpp_infer/tools/config.txt
doc/doc_ch/whl.md
doc/doc_en/whl_en.md
paddleocr.py

fix whl doc and add multi-language

---

tools/infer/predict_system.py
tools/infer/utility.py

fix visualize

---

ppocr/data/rec/img_tools.py
ppocr/data/rec/text_image_aug/augment.py
ppocr/data/rec/text_image_aug/warp_mls.py

add tia aug

---

deploy/slim/quantization/README.md

Update slim quant README.md

---

train_data/gen_label.py

fix gen label

---

deploy/cpp_infer/readme.md
deploy/cpp_infer/readme_en.md

improve cpp infer doc

---

tools/test_hubserving.py

fix hub serving draw

---

deploy/pdserving/clas_local_server.py
deploy/pdserving/clas_rpc_server.py
deploy/pdserving/ocr_local_server.py
deploy/pdserving/ocr_rpc_server.py
doc/doc_ch/serving_inference.md

Bug fixes
Others, Docs
1. 修改pdserving部署脚本的问题。
例如fetch var not found
2. 修改cls过程中旋转图片有bug的问题
3. 修改 [部署文档](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/serving_inference.md) 中部分路径不正确的情况
4. 修改Serving当中保存模型接口 lod为True，并粘贴beta wheel包到 [部署文档](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/serving_inference.md)  中

pdserving fetch var fix

---

deploy/android_demo/app/src/main/java/com/baidu/paddle/lite/demo/ocr/OCRPredictorNative.java

since it named "release" in native.cpp

fix method name bug

---

ppocr/data/rec/img_tools.py

fix tia exception

---

deploy/pdserving/clas_local_server.py
deploy/pdserving/clas_rpc_server.py
deploy/pdserving/ocr_local_server.py
deploy/pdserving/ocr_rpc_server.py
deploy/pdserving/rec_local_server.py
deploy/pdserving/rec_rpc_server.py

Bug Fixes
Others
去掉了pdserving脚本中调用OCRReader等多余代码。

pdserving remove OCRReader

---

ppocr/modeling/necks/rnn.py
ppocr/postprocess/rec_postprocess.py

1. crnn的neck添加im2seq实现
2. 解决crnn训练时对labels进行合并的bug

解决crnn训练时对labels进行合并的bug

---

deploy/cpp_infer/src/preprocess_op.cpp

fix cpp inference bug

---

README.md
README_ch.md
doc/doc_ch/quickstart.md
doc/doc_en/quickstart_en.md

fix serving link

---

deploy/slim/quantization/export_model.py
deploy/slim/quantization/quant.py
ppocr/modeling/architectures/cls_model.py

Add cls model quantization support.

support quant cls model in slim module

---

deploy/lite/readme_en.md

Missing spaces cause the anomaly display of the table in section 4.

Fix the table view in deploy/lite/readme_en.md

---

README.md
README_ch.md

add two contributors at the end of the readme

add two contributors at the end of the readme

---

deploy/pdserving/ocr_local_server.py
deploy/pdserving/ocr_rpc_server.py

Others
Function Optimiazation
增加了ocr串联服务时，输出坐标位置
示例输出
```
{'result': {'pos': [[[131.0, 27.0], [380.0, 27.0], [380.0, 58.0], [131.0, 58.0]], [[48.0, 64.0], [461.0, 65.0], [461.0, 85.0], [48.0, 84.0]], [[34.0, 89.0], [276.0, 89.0], [276.0, 108.0], [34.0, 108.0]], [[267.0, 92.0], [477.0, 92.0], [477.0, 108.0], [267.0, 108.0]], [[341.0, 208.0], [396.0, 206.0], [397.0, 229.0], [342.0, 231.0]], [[182.0, 298.0], [309.0, 292.0], [310.0, 314.0], [183.0, 320.0]]], 'pred_text': ['防止刮花再无划痕', '经过钢化处理，增强贴膜吸附性和柔软性，在易贴不脱的情况下', '同时科学防震缓冲硬物撞击，不裂开。', '。长期防止划痕的产生坚固耐用', '10:00', '休息的时候听听歌'], 'score': ['0.99890053', '0.9989576', '0.9952544', '0.98624647', '0.9790155', '0.99350846']}}
```

pdserving add box positions

---

ppocr/optimizer.py

add utility doc

---

README.md

revise readme_en

---

ppocr/data/cls/dataset_traversal.py

fix cuda default value

---

deploy/cpp_infer/src/preprocess_op.cpp

as title, keep constant with #985

fix -1 in det resize

---

doc/doc_ch/recognition.md
doc/doc_en/recognition_en.md

Correct spelling errors in doc

---

deploy/android_demo/app/build.gradle
deploy/android_demo/app/src/main/java/com/baidu/paddle/lite/demo/ocr/OCRPredictorNative.java
deploy/android_demo/app/src/main/java/com/baidu/paddle/lite/demo/ocr/Predictor.java

fix android demo

---

ppocr/utils/utility.py
tools/eval.py
tools/infer_cls.py
tools/infer_det.py
tools/infer_rec.py
tools/train.py

adapt codes to Paddle2.0-rc

---

configs/rec/ch_ppocr_v1.1/rec_chinese_lite_train_v1.1.yaml
ppocr/data/imaug/rec_img_aug.py
ppocr/data/simple_dataset.py

add ch lite yaml file

---

configs/rec/ch_ppocr_v1.1/rec_chinese_common_train_v1.1.yaml

add common ch config

---

tools/train.py

fix logger

---

tools/infer/predict_det.py

使predict_det.py文件在windows下正确运行，之前的代码假设了一些linux下的特性，造成在windows下无法正确运行。

make predict_det.py work on windows

---

doc/doc_ch/whl.md
doc/doc_en/whl_en.md

add paddlepaddle install guide

update whl doc

---

PPOCRLabel/Makefile
PPOCRLabel/README.md
PPOCRLabel/README_en.md
requirements.txt

As the new version of OpenCV(4.4.X) has conflicts with PYQT, the version of OpenCV needs to be specified.

Update installation steps and specify opencv version

---

deploy/slim/quantization/README.md
deploy/slim/quantization/README_en.md

Fix incorrect path of Mobile terminal model deployment in doc of quantization.

Fix path in doc of quantization

---

doc/doc_ch/algorithm_overview.md
doc/doc_ch/recognition.md
doc/doc_en/algorithm_overview_en.md
doc/doc_en/recognition_en.md

迁移readme到动态图文档，修复algorithm_overview的中英文文档

fix doc algorithm_overview ch&en

---

StyleText/README.md
StyleText/README_ch.md
StyleText/engine/predictors.py
StyleText/tools/synth_dataset.py
StyleText/tools/synth_image.py

add support for cpu infer

---

doc/doc_ch/angle_class.md
doc/doc_ch/detection.md
doc/doc_ch/inference.md
doc/doc_ch/recognition.md
doc/doc_en/angle_class_en.md
doc/doc_en/detection_en.md
doc/doc_en/inference_en.md
doc/doc_en/recognition_en.md

1. 更新inference文档
2. 检测，识别，方向分类器的文档里，预测部分统一使用pretrained_model来加载模型

update inference doc

---

PPOCRLabel/PPOCRLabel.py

set default use_gpu to False

---

README_ch.md
doc/doc_ch/FAQ.md

add faq 20201228

---

ppocr/metrics/rec_metric.py

fix space eval

---

README.md
README_ch.md

fix readme

---

ppocr/utils/utility.py

fix get image list

---

ppocr/postprocess/rec_postprocess.py

fix duplicate

---

paddleocr.py

fix ocr func for Chinese path issus

fix ocr func for Chinese path issus

---

ppocr/data/__init__.py
ppocr/data/lmdb_dataset.py
ppocr/data/simple_dataset.py
tools/program.py

fix data replication for multi-cards sampling

---

ppocr/modeling/backbones/det_mobilenet_v3.py
ppocr/modeling/backbones/rec_mobilenet_v3.py

fix mv3 to adapt to paddle2.0

---

ppocr/modeling/backbones/det_mobilenet_v3.py
ppocr/modeling/backbones/rec_mobilenet_v3.py

Reverts PaddlePaddle/PaddleOCR#1827

Revert "fix mv3 to adapt to paddle2.0"

---

StyleText/README.md
StyleText/README_ch.md

增加language选项的说明，中文(ch)，英文(en)和韩文(ko)

增加language选项的说明

---

doc/doc_ch/algorithm_overview.md
doc/doc_ch/inference.md
doc/doc_ch/recognition.md
doc/doc_en/algorithm_overview_en.md
doc/doc_en/inference_en.md
doc/doc_en/recognition_en.md

Add srn doc

---

configs/rec/rec_mv3_tps_bilstm_att.yml
configs/rec/rec_mv3_tps_bilstm_ctc.yml
configs/rec/rec_r34_vd_tps_bilstm_att.yml

fix typo for attention

---

tools/program.py

polish code for srn eval

---

ppocr/data/imaug/label_ops.py

Fix encode for srn and attn

---

deploy/lite/readme.md
deploy/lite/readme_en.md

fix lite doc

---

deploy/slim/prune/README.md
deploy/slim/prune/README_en.md
deploy/slim/prune/export_prune_model.py
deploy/slim/prune/sensitivity_anal.py

add prune demo

---

ppocr/data/imaug/make_shrink_map.py

fix issue https://github.com/PaddlePaddle/PaddleOCR/issues/2013 in dygraph

fix issue 2013

---

tools/infer/predict_rec.py

fix when the image list is too long(memory may be not enough)

fix predict rec

---

tools/test_hubserving.py

fix test_hubserving

---

deploy/cpp_infer/src/ocr_rec.cpp
ppocr/data/imaug/make_shrink_map.py

fix issue https://github.com/PaddlePaddle/PaddleOCR/issues/2072

fix issue 2072

---

README.md
README_ch.md

Change the path of joinus.png to absolute path

Change the path of joinus.png to absolute path

---

tools/infer/predict_det.py
tools/infer_det.py

fix issue #https://github.com/PaddlePaddle/PaddleOCR/issues/2080

fix gap between train_model predict and inference

---

configs/rec/multi_language/generate_multi_language_configs.py

fix type error in 2.0 release

---

configs/rec/multi_language/generate_multi_language_configs.py

fix type error

---

ppocr/utils/utility.py

fix issue https://github.com/PaddlePaddle/PaddleOCR/issues/2086

fix issue 2086

---

ppocr/data/imaug/randaugment.py

add prob for ra

---

tools/infer/predict_cls.py
tools/infer/predict_det.py
tools/infer/predict_rec.py

修复推理过程中的内存泄露问题

---

doc/doc_ch/algorithm_overview.md
doc/doc_en/algorithm_overview_en.md

add google drive link

---

ppocr/data/simple_dataset.py

fix eval res vary for different times

---

README_ch.md

revise the readme_ch

---

doc/doc_en/multi_languages_en.md

fix format for en doc

---

configs/rec/multi_language/generate_multi_language_configs.py
doc/doc_ch/multi_languages.md
doc/doc_en/multi_languages_en.md
paddleocr.py
ppocr/data/imaug/label_ops.py
ppocr/postprocess/rec_postprocess.py

fix some typo

---

ppocr/utils/e2e_utils/extract_textpoint_fast.py
tools/program.py

att, the following is the log after the change, which is same as before between 2 epochs.

fix loader cause it does not need to break

---

doc/doc_ch/inference.md
doc/doc_en/inference_en.md

add infer mp doc

---

ppocr/postprocess/db_postprocess.py
tools/infer/predict_det.py
tools/infer/utility.py

add py impl of pr 2574

---

deploy/cpp_infer/include/postprocess_op.h
deploy/cpp_infer/src/postprocess_op.cpp
ppocr/postprocess/db_postprocess.py
tools/infer/predict_det.py
tools/infer/utility.py

add new db post score calculation method

---

deploy/hubserving/ocr_cls/module.py
deploy/hubserving/ocr_det/module.py
deploy/hubserving/ocr_det/params.py
deploy/hubserving/ocr_rec/module.py
deploy/hubserving/ocr_system/module.py
deploy/hubserving/ocr_system/params.py

fix hub serving for db post process

---

deploy/hubserving/ocr_cls/module.py
deploy/hubserving/ocr_det/module.py
deploy/hubserving/ocr_det/params.py
deploy/hubserving/ocr_rec/module.py
deploy/hubserving/ocr_system/module.py
deploy/hubserving/ocr_system/params.py

fix hub post

---

paddleocr.py

fix db post for whl

---

configs/rec/ch_ppocr_v2.0/rec_chinese_common_train_v2.0.yml
configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml
configs/rec/rec_icdar15_train.yml
configs/rec/rec_mv3_none_bilstm_ctc.yml
configs/rec/rec_mv3_none_none_ctc.yml
configs/rec/rec_mv3_tps_bilstm_att.yml
configs/rec/rec_mv3_tps_bilstm_ctc.yml
configs/rec/rec_r34_vd_none_bilstm_ctc.yml
configs/rec/rec_r34_vd_none_none_ctc.yml
configs/rec/rec_r34_vd_tps_bilstm_att.yml
configs/rec/rec_r34_vd_tps_bilstm_ctc.yml
configs/rec/rec_r50_fpn_srn.yml
deploy/hubserving/ocr_cls/module.py
tools/infer_rec.py

att
```
doc/imgs_words/ch/word_1.jpg	韩国小馆	0.9972599
doc/imgs_words/ch/word_2.jpg	汉阳鹦鹉家居建材市场E区25-26号	0.98325264
doc/imgs_words/ch/word_3.jpg	电话：15952301928	0.9954566
doc/imgs_words/ch/word_4.jpg	实力活力	0.9792933
doc/imgs_words/ch/word_5.jpg	西湾监管	0.9851265
```

add save rec res

---

deploy/hubserving/ocr_cls/module.py

fix cls hub

---

deploy/cpp_infer/include/config.h
deploy/cpp_infer/include/ocr_det.h
deploy/cpp_infer/include/postprocess_op.h
deploy/cpp_infer/readme.md
deploy/cpp_infer/readme_en.md
deploy/cpp_infer/src/main.cpp
deploy/cpp_infer/src/ocr_det.cpp
deploy/cpp_infer/src/postprocess_op.cpp
deploy/cpp_infer/tools/config.txt

cherry-pick https://github.com/PaddlePaddle/PaddleOCR/pull/2646

Add polygon score param to config 

---

tools/program.py

fix eval laoder on win

---

doc/doc_ch/multi_languages.md

fix mult-doc link

---

deploy/cpp_infer/src/postprocess_op.cpp

Update postprocess_op.cpp to adapt to vc++

---

doc/doc_ch/multi_languages.md
ppocr/modeling/heads/self_attention.py

fix srn for https://github.com/PaddlePaddle/Paddle/pull/31824/files

Fix srn for sublayers

---

doc/doc_ch/FAQ.md
ppocr/modeling/backbones/rec_resnet_vd.py

1. fix onnx doc
2. cherry-pick #2681

fix onnx faq

---

deploy/cpp_infer/src/postprocess_op.cpp
tools/program.py

1. cherry-pick #2665 
2. cherry-pick #2669

cherry-pick users' pr

---

ppocr/modeling/heads/self_attention.py

update for paddle2.1

---

ppocr/modeling/heads/self_attention.py

[Cherry pick] fix srn for sub_layers

---

configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml
configs/det/ch_ppocr_v2.0/ch_det_res18_db_v2.0.yml
configs/det/det_mv3_db.yml
configs/det/det_mv3_east.yml
configs/det/det_r50_vd_db.yml
configs/det/det_r50_vd_east.yml
configs/det/det_r50_vd_sast_icdar15.yml
configs/det/det_r50_vd_sast_totaltext.yml
configs/e2e/e2e_r50_vd_pg.yml
doc/doc_ch/detection.md
doc/doc_ch/inference.md
doc/doc_en/detection_en.md
doc/doc_en/inference_en.md

* delete load_static_weights for detection
* master to develop for PaddleClas referencee

[cherry-pick] delete load_static_weights for detection (#2725)

---

doc/doc_en/quickstart_en.md

Modify some expressions in quickstart_en.md

Modify some expressions in quickstart_en.md

---

doc/doc_ch/distributd_training.md
doc/doc_ch/distributed_training.md

att. acceleration ratio can reach 150% when using 2 machine.

add distributed training doc

---

doc/doc_en/quickstart_en.md

fix dead link

---

deploy/lite/Makefile

- Paddle-Lite C++ demo can not compile successfully

[Paddle-Lite DEMO] Fix the issue that Paddle-Lite C++ demo can not compile successfully

---

deploy/pdserving/README.md
deploy/pdserving/README_CN.md

doc fix
- 更改pdserving 关于Windows描述

fix windows readme

---

deploy/pdserving/README.md
deploy/pdserving/README_CN.md

cherry-pick #2850 to release/2.1

Cherry pick 2.1

---

deploy/cpp_infer/src/ocr_rec.cpp

fix cpp order

---

configs/rec/ch_ppocr_v2.1/rec_chinese_lite_train_distillation_v2.1.yml
ppocr/modeling/heads/rec_ctc_head.py
tools/eval.py

add embedding and fix eval when distillation

---

deploy/cpp_infer/src/preprocess_op.cpp

att. 5s/img -> 4.5s/img for the test_sum510 using CPU+mkldnn

fix normalize

---

configs/rec/ch_ppocr_v2.1/rec_chinese_lite_train_distillation_v2.1.yml
doc/doc_ch/knowledge_distillation.md
ppocr/modeling/backbones/__init__.py
ppocr/modeling/backbones/rec_mv1_enhance.py

add mv1 enhance backbone

---

deploy/slim/quantization/export_model.py
deploy/slim/quantization/quant.py

1. fix bug cause eval function interface is changed.
2. add support for distillation model quant and export.

add support for quant distillation

---

deploy/hubserving/readme.md
deploy/hubserving/readme_en.md
tools/infer/predict_det.py
tools/infer/predict_system.py

fix bug of inference

---

configs/det/ch_ppocr_v2.1/ch_det_lite_train_cml_v2.1.yml
configs/det/ch_ppocr_v2.1/ch_det_lite_train_distill_v2.1.yml
configs/det/ch_ppocr_v2.1/ch_det_lite_train_dml_v2.1.yml
ppocr/losses/basic_loss.py
ppocr/losses/combined_loss.py
ppocr/losses/distillation_loss.py
ppocr/metrics/det_metric.py
ppocr/metrics/distillation_metric.py
ppocr/modeling/architectures/base_model.py
ppocr/modeling/architectures/distillation_model.py
ppocr/postprocess/__init__.py
ppocr/postprocess/db_postprocess.py
ppocr/utils/save_load.py
tools/eval.py
tools/program.py
tools/train.py

Add det distill

---

doc/doc_en/update_en.md
test/ocr_rec_params.txt
test/prepare.sh
tools/infer/predict_rec.py

1. Add autolog for infer_rec
2. fix #1706

add autolog for infer_rec

---

doc/doc_ch/recognition.md
doc/doc_en/recognition_en.md

Fix multi yml doc

---

deploy/cpp_infer/docs/windows_vs2019_build.md

improve doc for cpp infer on windows

---

ppocr/data/imaug/label_ops.py
tools/infer/utility.py

1. 修复label为空时，eval报错的问题；
2. 保持训练和infer时DB后处理参数不一致的问题

Fix qa bugs

---

tools/infer/utility.py

change dynameic shape

---

tools/infer/utility.py

add dynamic_input for pact

---

tools/export_model.py
tools/infer_rec.py

1. 导出模型的时候，只需要导出最终模型的输出即可
2. float类型的输出才可以被dump到json中，np不行

fix distillation model export and pred save

---

tests/ocr_det_params.txt
tests/prepare.sh
tests/test.sh

- infer 模式下将动转静加入到测试过程中
- 动转静的状态检查设置为默认
- infer 模式下CPU的线程数设置从1|6改成6，去掉CPU线程数为1的检查，加速运行

add export model for infer MODE

---

doc/doc_ch/angle_class.md
doc/doc_en/angle_class_en.md

format angle_class

---

tests/configs/rec_icdar15_r34_train.yml
tests/ocr_ppocr_server_params.txt
tests/ocr_rec_params.txt
tests/ocr_rec_server_params.txt
tests/prepare.sh

* add rec params for serving
* add ppocr_server_model for ci

polish tests for rec and server

---

configs/rec/rec_r31_sar.yml

update evaluation data path in `sar` config

update sar config

---

tests/test.sh

fix type for serving

---

ppocr/modeling/heads/rec_sar_head.py

fix set value when slice index greater than length in `rec_sar_head.py`

fix slice in sar head

---

doc/doc_ch/detection.md
doc/doc_en/detection_en.md

Fix a serious doc issue

---

ppocr/postprocess/__init__.py
tools/program.py

At present, there are still some problems after compiling pse post-process under Windows. When users train pse under Windows,  show hint msg that the "pse algorithm is not supported under Windows"

add pse to windows_not_support_list

---

tools/export_model.py
tools/infer/predict_rec.py

fix `sar` export inference model

fix sar export inference model

---

configs/rec/rec_resnet_stn_bilstm_att.yml
ppocr/modeling/backbones/__init__.py
tools/program.py

Fix some typo for SEED

---

ppocr/modeling/backbones/rec_resnet_31.py
ppocr/modeling/heads/rec_sar_head.py

add refer to `rec_resnet_31.py` and `rec_sar_head.py`

add refer to backbone and head of sar

---

deploy/pdserving/README.md
deploy/pdserving/README_CN.md
ppocr/modeling/backbones/rec_resnet_aster.py
ppocr/modeling/heads/rec_aster_head.py
ppocr/modeling/transforms/stn.py
ppocr/modeling/transforms/tps_spatial_transformer.py

Add refer for seed

---

ppocr/losses/ace_loss.py
ppocr/losses/center_loss.py
ppocr/modeling/backbones/rec_mv1_enhance.py

add reference

---

ppocr/modeling/heads/rec_att_head.py

add softmax for correcting attention's score

fix attn score

---

ppocr/modeling/heads/rec_att_head.py

cherry-pick #4556 to release/2.3

[cherry-pick] fix attn score

---

ppocr/modeling/backbones/rec_mv1_enhance.py

[cherry-pick 4552] add reference

---

deploy/pdserving/ocr_cpp_client.py
deploy/pdserving/pipeline_http_client.py
deploy/pdserving/pipeline_rpc_client.py
test_tipc/configs/mac_ppocr_det_mobile_params.txt
test_tipc/configs/ppocr_det_mobile_params.txt
test_tipc/configs/ppocr_det_server_params.txt
test_tipc/configs/ppocr_rec_mobile_params.txt
test_tipc/configs/ppocr_rec_server_params.txt
test_tipc/configs/win_ppocr_det_mobile_params.txt
test_tipc/test_lite.sh
test_tipc/test_serving.sh
test_tipc/test_train_inference_python.sh

1. add rpc in test_tipc
2. add ocr_cpp_client

update test serving

---

test_tipc/configs/ppocr_det_mobile/model_linux_gpu_normal_normal_paddle2onnx_python_linux_cpu.txt
test_tipc/configs/ppocr_det_server/model_linux_gpu_normal_normal_paddle2onnx_python_linux_cpu.txt
test_tipc/configs/ppocr_det_server/model_linux_gpu_normal_normal_serving_python_linux_gpu_cpu.txt
test_tipc/configs/ppocr_rec_mobile/model_linux_gpu_normal_normal_paddle2onnx_python_linux_cpu.txt
test_tipc/configs/ppocr_rec_mobile/model_linux_gpu_normal_normal_serving_python_linux_gpu_cpu.txt
test_tipc/configs/ppocr_rec_server/model_linux_gpu_normal_normal_paddle2onnx_python_linux_cpu.txt
test_tipc/configs/ppocr_rec_server/model_linux_gpu_normal_normal_serving_python_linux_gpu_cpu.txt
test_tipc/docs/test_paddle2onnx.md
test_tipc/docs/test_serving.md
test_tipc/test_paddle2onnx.sh
test_tipc/test_serving.sh

rename params for serving and paddle2onnx

---

doc/doc_ch/detection.md
doc/doc_en/detection_en.md

add statement of activating commands separately on multi machine.

update detection.md of ch and en

---

ppocr/data/imaug/label_ops.py
ppocr/modeling/heads/rec_att_head.py

[cherry-pick] fix attn loss for ce

---

deploy/cpp_infer/readme.md
deploy/cpp_infer/readme_en.md
deploy/cpp_infer/tools/build_opencv.sh
tools/infer/predict_e2e.py
tools/infer/utility.py

fix cpp infer doc

---

ppocr/modeling/heads/rec_att_head.py

Fix att loss

---

benchmark/run_benchmark_det.sh
benchmark/run_det.sh

Update ocr scripts for benchmark

---

test_tipc/configs/rec_mtb_nrtr/rec_mtb_nrtr.yml
test_tipc/configs/rec_mtb_nrtr/train_infer_python.txt
test_tipc/configs/rec_mv3_tps_bilstm_att_v2.0/rec_mv3_tps_bilstm_att.yml
test_tipc/configs/rec_mv3_tps_bilstm_att_v2.0/train_infer_python.txt
test_tipc/configs/rec_r31_sar/rec_r31_sar.yml
test_tipc/configs/rec_r31_sar/train_infer_python.txt
test_tipc/configs/rec_r34_vd_tps_bilstm_att_v2.0/rec_r34_vd_tps_bilstm_att.yml
test_tipc/configs/rec_r34_vd_tps_bilstm_att_v2.0/train_infer_python.txt
test_tipc/configs/rec_r50_fpn_vd_none_srn/rec_r50_fpn_srn.yml
test_tipc/configs/rec_r50_fpn_vd_none_srn/train_infer_python.txt

add RARE, SRN, SAR, NRTR model to tipc

add rec attention model to tipc

---

tools/infer_det.py

add no_grad for infer function

---

benchmark/run_benchmark_det.sh
benchmark/run_det.sh

* fix log_name
* update bs 
db 模型训练 8  16
pse 和 east 只保留较大的16

fix_log_name

---

doc/doc_ch/inference.md
doc/doc_ch/pgnet.md
doc/doc_en/pgnet_en.md

fix pgnet doc

---

tools/infer/utility.py

fix rec trt dynamic shape error

fix rec trt dynamic shape error

---

test_tipc/configs/rec_mv3_tps_bilstm_ctc_v2.0/train_infer_python.txt
test_tipc/configs/rec_r34_vd_tps_bilstm_ctc_v2.0/train_infer_python.txt

fix tps_ctc model for test_tipc

---

PPOCRLabel/libs/canvas.py

更改PPOCRLabel/libs/canvas.py文件，修复未打开文件或打开未标注文件，点击按键闪退

Modify the bug

---

test_tipc/configs/rec_mtb_nrtr/train_infer_python.txt
test_tipc/configs/rec_mv3_tps_bilstm_att_v2.0/train_infer_python.txt
test_tipc/configs/rec_r31_sar/train_infer_python.txt
test_tipc/configs/rec_r34_vd_tps_bilstm_att_v2.0/train_infer_python.txt
test_tipc/configs/rec_r50_fpn_vd_none_srn/train_infer_python.txt

fix rec attn oom

---

deploy/pdserving/README.md
deploy/pdserving/README_CN.md

fix dead link for serving

---

configs/det/ch_PP-OCRv2/ch_PP-OCRv2_det_cml.yml
deploy/slim/quantization/export_model.py
test_tipc/configs/ch_ppocr_server_v2.0_det/train_infer_python.txt

fix det slim export error and some wrong dir name

fix det slim export

---

test_tipc/configs/det_r50_vd_pse_v2.0/train_infer_python.txt
test_tipc/prepare.sh

[tipc] fix some data dir error in `whole infer` model

[tipc] fix some data dir error in `whole infer` model

---

test_tipc/configs/ch_PP-OCRv2_rec/train_infer_python.txt
test_tipc/configs/ch_PP-OCRv2_rec_PACT/train_infer_python.txt
test_tipc/configs/ch_ppocr_mobile_v2.0_det/train_infer_python.txt
test_tipc/configs/ch_ppocr_mobile_v2.0_rec_FPGM/train_infer_python.txt
test_tipc/configs/ch_ppocr_mobile_v2.0_rec_PACT/train_infer_python.txt
test_tipc/prepare.sh

fix some wrong data dir in `whole infer` mode

[tipc] fix some wrong data dir

---

test_tipc/test_inference_cpp.sh
test_tipc/test_inference_python.sh
test_tipc/test_train_inference_python.sh

fix mkldnn in tipc

---

test_tipc/configs/ch_PP-OCRv2_det/train_infer_python.txt
test_tipc/configs/ch_PP-OCRv2_det_PACT/train_infer_python.txt
test_tipc/configs/ch_PP-OCRv2_rec_PACT/train_infer_python.txt
test_tipc/configs/ch_ppocr_mobile_v2.0_det_PACT/train_infer_python.txt
test_tipc/configs/ch_ppocr_mobile_v2.0_rec_PACT/train_infer_python.txt
test_tipc/configs/det_mv3_east_v2.0/train_infer_python.txt
test_tipc/configs/det_mv3_pse_v2.0/train_infer_python.txt
test_tipc/configs/det_r50_vd_east_v2.0/train_infer_python.txt
test_tipc/prepare.sh

fix PACT model dir

---

test_tipc/configs/ch_ppocr_server_v2.0_rec/train_infer_python.txt
test_tipc/configs/rec_mv3_none_bilstm_ctc_v2.0/train_infer_python.txt
test_tipc/configs/rec_mv3_none_none_ctc_v2.0/train_infer_python.txt
test_tipc/configs/rec_mv3_tps_bilstm_ctc_v2.0/train_infer_python.txt
test_tipc/configs/rec_r34_vd_none_bilstm_ctc_v2.0/train_infer_python.txt
test_tipc/configs/rec_r34_vd_none_none_ctc_v2.0/train_infer_python.txt
test_tipc/configs/rec_r34_vd_tps_bilstm_ctc_v2.0/train_infer_python.txt
test_tipc/prepare.sh

Support whole infer for rec_ctc

---

test_tipc/configs/ch_ppocr_mobile_v2.0_rec/train_infer_python.txt
test_tipc/configs/rec_mtb_nrtr/train_infer_python.txt
test_tipc/configs/rec_mv3_tps_bilstm_att_v2.0/train_infer_python.txt
test_tipc/configs/rec_r31_sar/train_infer_python.txt
test_tipc/configs/rec_r34_vd_tps_bilstm_att_v2.0/train_infer_python.txt
test_tipc/configs/rec_r50_fpn_vd_none_srn/train_infer_python.txt
test_tipc/prepare.sh

fix `whole infer` for rec attn

[TIPC] fix whole infer for rec attn

---

test_tipc/configs/ch_PP-OCRv2_rec/train_infer_python.txt
test_tipc/configs/ch_PP-OCRv2_rec_PACT/train_infer_python.txt
test_tipc/configs/ch_ppocr_mobile_v2.0_rec/train_infer_python.txt
test_tipc/configs/ch_ppocr_mobile_v2.0_rec_PACT/train_infer_python.txt

fix wrong args for ch_ppocr_mobile_v2.0_rec

[TIPC] fix wrong args for some model

---

test_tipc/configs/ch_PP-OCRv2_rec/train_infer_python.txt
test_tipc/configs/ch_PP-OCRv2_rec_PACT/train_infer_python.txt
test_tipc/configs/ch_ppocr_mobile_v2.0_rec/train_infer_python.txt
test_tipc/configs/ch_ppocr_mobile_v2.0_rec_PACT/train_infer_python.txt
test_tipc/configs/rec_r31_sar/train_infer_python.txt

[TIPC] remove fp16 for rec model

---

configs/rec/ch_ppocr_v2.0/rec_chinese_common_train_v2.0.yml
configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml

fix warmup

---

configs/rec/rec_resnet_stn_bilstm_att.yml
ppocr/data/imaug/label_ops.py
ppocr/modeling/heads/rec_aster_head.py
ppocr/postprocess/rec_postprocess.py

polist seed code

---

ppstructure/vqa/eval_re.py
ppstructure/vqa/eval_ser.py
ppstructure/vqa/infer_re.py
ppstructure/vqa/infer_ser.py
ppstructure/vqa/infer_ser_e2e.py
ppstructure/vqa/infer_ser_re_e2e.py
ppstructure/vqa/train_re.py
ppstructure/vqa/train_ser.py
ppstructure/vqa/vqa_utils.py

fix vq utils

---

ppstructure/vqa/eval_re.py
ppstructure/vqa/eval_ser.py
ppstructure/vqa/infer_re.py
ppstructure/vqa/infer_ser.py
ppstructure/vqa/infer_ser_e2e.py
ppstructure/vqa/infer_ser_re_e2e.py
ppstructure/vqa/train_re.py
ppstructure/vqa/train_ser.py
ppstructure/vqa/vqa_utils.py

fix vqa utils

---

tools/program.py

add a constraint to avoid some problems

add a constraint

---

README.md
README_ch.md
notebook/notebook_ch/如何使用本书.ipynb

Upload notebook

---

doc/doc_ch/data_synthesis.md
doc/doc_en/data_synthesis_en.md

Introduce a new synthesis engine.
SynthTIGER is a new synthesis engine for scene text recognition. (https://github.com/clovaai/synthtiger)
This engine achieves better performance than MJSynth + SynthText.
In addition, this engine supports for multilingual (e.g. scripts using diacritics, ligature, right to left) and vertical text.
I hope to make it easy for users to develop OCR models using this engine.
Thanks.

Add new synthesis engine

---

test_tipc/configs/ch_ppocr_mobile_V2.0_det_FPGM/train_infer_python.txt
test_tipc/configs/ch_ppocr_mobile_v2.0_det/train_infer_python.txt
test_tipc/configs/ch_ppocr_mobile_v2.0_rec_FPGM/train_infer_python.txt
test_tipc/configs/ch_ppocr_server_v2.0_det/train_infer_python.txt
test_tipc/configs/det_mv3_db_v2.0/train_infer_python.txt
test_tipc/configs/det_mv3_east_v2.0/train_infer_python.txt
test_tipc/configs/det_mv3_pse_v2.0/train_infer_python.txt
test_tipc/configs/det_r50_db_v2.0/train_infer_python.txt
test_tipc/configs/det_r50_vd_east_v2.0/train_infer_python.txt
test_tipc/configs/det_r50_vd_pse_v2.0/train_infer_python.txt
test_tipc/configs/det_r50_vd_sast_icdar15_v2.0/train_infer_python.txt
test_tipc/configs/det_r50_vd_sast_totaltext_v2.0/train_infer_python.txt
test_tipc/configs/en_server_pgnetA/train_infer_python.txt

fix infinite for pgnet and some wrong model dir

[TIPC] fix infinite for pgnet and some wrong model dir

---

tools/infer/utility.py

Set proper GPU device under windows.

fix  #5065

---

doc/doc_ch/recognition.md
ppocr/data/imaug/operators.py
requirements.txt

[cherrr-pick] mv fasttext for requirments

---

ppocr/data/imaug/operators.py
requirements.txt

mv fasttext for requirements

---

doc/doc_ch/detection.md
doc/doc_en/detection_en.md
ppocr/utils/save_load.py

fix save load, update det pretrain

---

doc/doc_ch/knowledge_distillation.md
doc/doc_en/knowledge_distillation_en.md

translate  knowledge_distillation_en.md

---

test_tipc/prepare.sh

add data dir for `PPOCRv2_ocr_rec_kl`

[TIPC] add data dir for PPOCRv2_ocr_rec_kl

---

test_tipc/configs/ch_PP-OCRv2_det_KL/model_linux_gpu_normal_normal_infer_python_linux_gpu_cpu.txt

fix wrong path

---

tools/program.py

fix vdl makedir

---

doc/doc_ch/code_and_doc.md
doc/doc_en/code_and_doc_en.md
doc/doc_en/community_contribution_en.md

https://github.com/PaddlePaddle/PaddleOCR/pull/5119
add doc/doc_en/code_and_doc_en.md
add doc/doc_en/communication_contribution_en.md
update doc/doc_ch/code_and_doc.md

同步dygraph分支的修改到release2.4分支

---

doc/doc_ch/thirdparty.md

应用于OCR场景的前处理工具集，具有：1.旋转图像、2.腐蚀膨胀、3.图片反色、4.缩放、5.二值化、6.去倾斜、7.去噪等功能。

【third-party】optlab，OCR前处理工具箱，基于Qt和Leptonica。

---

doc/doc_ch/thirdparty.md

【third-party】PaddleOCR的.NET封装与应用部署

---

doc/doc_ch/thirdparty.md

【third-party】Add PaddleSharp as 3rd-party deployment.

---

doc/doc_ch/thirdparty.md

【Third Party】添加lmdb数据格式转换工具

---

doc/doc_en/enhanced_ctc_loss_en.md
ppstructure/docs/kie_en.md

Create kie_en.md and enhanced_ctc_loss_en.md
@Evezerest 
> https://github.com/PaddlePaddle/PaddleOCR/pull/5086#pullrequestreview-856250234

[doc][third-party] Create kie_en.md and enhanced_ctc_loss_en.md

---

tools/infer/predict_system.py

att, support to save results for the system prediction

add system pred save

---

doc/doc_ch/thirdparty.md

https://github.com/PaddlePaddle/PaddleOCR/pull/5349#issuecomment-1021777966
@Evezerest

【third-party】Add PaddleSharp.

---

deploy/cpp_infer/include/config.h
deploy/cpp_infer/include/ocr_rec.h
deploy/cpp_infer/src/main.cpp
deploy/cpp_infer/src/ocr_rec.cpp
deploy/cpp_infer/tools/config.txt

添加C++预测，批量识别代码。处理流程：得到检测结果后box按照宽度排序，width四像素对齐，图像按照最大宽度补零后传入batch

添加C++预测，批量识别代码

---

doc/doc_ch/thirdparty.md

参照[https://github.com/PaddlePaddle/PaddleOCR/issues/4982#issuecomment-1002833950](url)
@Evezerest

【third-party】LCD液晶字符检测

---

PPOCRLabel/README.md
PPOCRLabel/README_ch.md
PPOCRLabel/gen_ocr_train_val_test.py

修改完成:划分det与rec数据集

---

PPOCRLabel/README.md
PPOCRLabel/README_ch.md
PPOCRLabel/gen_ocr_train_val_test.py

修改完成:划分det与rec数据集脚本，以及对应的中英文文档指令及其数据集存放树状结构。已提交过release2.4分支

修改完成:划分det与rec数据集脚本，以及对应的中英文文档指令及其数据集存放树状结构。已提交过release2.4分支

---

doc/doc_ch/thirdparty.md

Update url link

---

doc/doc_ch/thirdparty.md

【third-party】用paddleocr打造一款“盗幕笔记”

---

doc/doc_ch/thirdparty.md

Add HustBestCat into the notebook translators.

将HustBestCat添加到notebook翻译者中

---

doc/doc_ch/thirdparty.md

Add docs contribution

---

doc/doc_ch/thirdparty.md

Add community standing

---

PPOCRLabel/PPOCRLabel.py
PPOCRLabel/README.md
PPOCRLabel/README_ch.md
PPOCRLabel/libs/canvas.py
PPOCRLabel/libs/keyDialog.py
PPOCRLabel/libs/labelColor.py
PPOCRLabel/libs/shape.py
PPOCRLabel/libs/unique_label_qlist_widget.py
PPOCRLabel/libs/utils.py
PPOCRLabel/resources/strings/strings-en.properties
PPOCRLabel/resources/strings/strings-zh-CN.properties

再次感谢 PaddleOCR 的开源，项目非常棒！本次 `PR` 主要是在 PPOCRLabel 中新增 KIE 的打标签功能，详细如下：
1. 主界面左下新增 `KeyList`
2. 点击【自动标注】之后 `KeyList` 会新增 `"None"`
3. 保存的 Json 加入 `key_cls` 字段
4. 打标签的时候会弹出 `KeyDialog` 来选择 `Key`
5. `KeyDialog` 确定 `Key` 之后，`Box` 会自动变色
6. 新增的 `key` 会增加到 `KeyList` 中
7. `KeyList` 不会重复显示 `Key` 
8. 重新启动的时候，自动加载所有的 `Key` 类别到 `KeyList`，并且对应的 `Box` 会根据 `Key` 变色
9. 右键新增 `Box` 修改 `Key` 类型
10. 点击 `Box` 的时候，`KeyList` 会同步选中那个 `Key`
UI 展示，不同的关键词用不用的框框选了
标签 Json 例子

NEW Feature: Add KIE function at PPOCRLabel 🚀 

---

test_tipc/configs/ch_PP-OCRv2_rec/train_infer_python.txt
test_tipc/configs/ch_PP-OCRv2_rec_PACT/train_infer_python.txt
test_tipc/configs/ch_ppocr_mobile_v2.0_rec/train_infer_python.txt
test_tipc/configs/ch_ppocr_mobile_v2.0_rec_FPGM/train_infer_python.txt
test_tipc/configs/ch_ppocr_mobile_v2.0_rec_PACT/train_infer_python.txt
test_tipc/configs/ch_ppocr_server_v2.0_rec/train_infer_python.txt
test_tipc/configs/rec_mtb_nrtr/train_infer_python.txt
test_tipc/configs/rec_mv3_none_bilstm_ctc_v2.0/train_infer_python.txt
test_tipc/configs/rec_mv3_none_none_ctc_v2.0/train_infer_python.txt
test_tipc/configs/rec_mv3_tps_bilstm_att_v2.0/train_infer_python.txt
test_tipc/configs/rec_mv3_tps_bilstm_ctc_v2.0/train_infer_python.txt
test_tipc/configs/rec_r31_sar/train_infer_python.txt
test_tipc/configs/rec_r34_vd_none_bilstm_ctc_v2.0/train_infer_python.txt
test_tipc/configs/rec_r34_vd_none_none_ctc_v2.0/train_infer_python.txt
test_tipc/configs/rec_r34_vd_tps_bilstm_att_v2.0/train_infer_python.txt
test_tipc/configs/rec_r34_vd_tps_bilstm_ctc_v2.0/train_infer_python.txt
test_tipc/configs/rec_r50_fpn_vd_none_srn/train_infer_python.txt

add infer benchmark params for rec model

[TIPC] add infer benchmark params for rec model

---

ppocr/losses/basic_loss.py

替换`F.kl_div`为自定义实现，保证x在stop grad=true的模式下，也可以计算loss
对比单测
```python
import paddle
import paddle.nn as nn
import paddle.nn.functional as F
def _kldiv(x, target):
loss = target * (paddle.log(target) - x)
loss = paddle.sum(loss) / loss.shape[0]
return loss
paddle.seed(0)
x = paddle.rand([32, 80, 1000])
y = paddle.rand([32, 80, 1000])
x = F.softmax(x, axis=-1)
y = F.softmax(y, axis=-1)
log_x = paddle.log(x)
log_y = paddle.log(y)
loss_me = _kldiv(log_x, y) + _kldiv(log_y, x)
loss_paddle = F.kl_div(log_x, y, reduction="batchmean") + \
F.kl_div(log_y, x, reduction="batchmean")
print(loss_me)
print(loss_paddle)
```
期望输出
```
Tensor(shape=[1], dtype=float32, place=CUDAPlace(0), stop_gradient=True,
[13.09558487])
Tensor(shape=[1], dtype=float32, place=CUDAPlace(0), stop_gradient=True,
[13.09558487]) …
```

fix kldiv when stop grad of x is true

---

ppocr/losses/basic_loss.py

fix kldiv when stop grad is true

---

doc/doc_ch/multi_languages.md

fix multi-lang doc

---

test_tipc/benchmark_train.sh

fix benchmark
benchmark中删除 run_process_type 区分，故删掉 benchmark_train.sh 中相关内容

fix benchmark

---

deploy/pdserving/README.md
deploy/pdserving/README_CN.md
deploy/pdserving/config.yml
deploy/pdserving/web_service_det.py
deploy/pdserving/web_service_rec.py
test_tipc/docs/test_serving.md

fix tipc serving doc

---

ppstructure/README.md
ppstructure/README_ch.md
ppstructure/docs/models_list.md

1. add pretrain model to ppyolov2_r50vd_dcn_365e_publaynet
2. add label map to layout model

[PP-Structure] update PP-Structure layout model link

---

deploy/pdserving/ocr_reader.py
deploy/pdserving/web_service_det.py
deploy/pdserving/web_service_rec.py
test_tipc/configs/ch_ppocr_mobile_v2.0_det/model_linux_gpu_normal_normal_serving_python_linux_gpu_cpu.txt
test_tipc/configs/ch_ppocr_mobile_v2.0_rec/model_linux_gpu_normal_normal_serving_python_linux_gpu_cpu.txt
test_tipc/configs/ch_ppocr_server_v2.0_det/model_linux_gpu_normal_normal_serving_python_linux_gpu_cpu.txt
test_tipc/configs/ch_ppocr_server_v2.0_rec/model_linux_gpu_normal_normal_serving_python_linux_gpu_cpu.txt
test_tipc/prepare.sh
test_tipc/test_serving.sh

polish tipc serving

---

__init__.py
paddleocr.py

[whl] add relative import 

---

ppocr/postprocess/rec_postprocess.py

change post process realization
```python
python tools/infer/predict_rec.py --rec_model_dir=./inference/ch_PP-OCRv2_rec_infer --image_dir=./doc/imgs_words/ch/
```
* Before the change
```
[2022/03/23 14:30:11] root INFO: Predicts of ./doc/imgs_words/ch/word_1.jpg:('韩国小馆', 0.9977643)
[2022/03/23 14:30:11] root INFO: Predicts of ./doc/imgs_words/ch/word_2.jpg:('汉阳鹦鹉家居建材市场E区25-26号', 0.99590206)
[2022/03/23 14:30:11] root INFO: Predicts of ./doc/imgs_words/ch/word_3.jpg:('电话：15952301928', 0.9924098)
[2022/03/23 14:30:11] root INFO: Predicts of ./doc/imgs_words/ch/word_4.jpg:('实力活力', 0.98046446)
[2022/03/23 14:30:11] root INFO: Predicts of ./doc/imgs_words/ch/word_5.jpg:('西湾监管', 0.9305527)
```
* After the change
```
[2022/03/23 14:34:05] ppocr INFO: Predicts of …
```

improve post process

---

tools/infer/predict_det.py

fix cross lines problems mentioned in https://github.com/PaddlePaddle/PaddleOCR/issues/5752

fix order_points_clockwise

---

deploy/slim/quantization/quant.py

fix quant logic

---

ppocr/modeling/heads/rec_sar_head.py

fix sar bug

---

doc/doc_ch/recognition.md
requirements.txt

rm fasttext

---

deploy/cpp_infer/include/ocr_det.h
deploy/cpp_infer/include/ocr_rec.h
deploy/cpp_infer/include/utility.h
deploy/cpp_infer/readme.md
deploy/cpp_infer/readme_en.md
deploy/cpp_infer/src/main.cpp
deploy/cpp_infer/src/ocr_det.cpp
deploy/cpp_infer/src/ocr_rec.cpp
deploy/cpp_infer/src/utility.cpp

The  contains the following
1. CRNNRecognizer support return txts and scores;
2. Support saving the visual results of detection to a specified directory, the saved file name of the visualization result is the same as the input image

rec return result

---

paddleocr.py

update paddleocr version no

---

README.md
README_ch.md

Lgc 2.4 dev

---

test_tipc/configs/rec_r31_sar/train_infer_python.txt

[TIPC] fix sar infer benchmark

---

test_tipc/configs/rec_r34_vd_tps_bilstm_att_v2.0/train_infer_python.txt
tools/infer/predict_rec.py
tools/infer/utility.py

[tipc] fix rare tensorrt shape error

---

test_tipc/configs/rec_r50_fpn_vd_none_srn/train_infer_python.txt

[tipc] fix srn trt shape error

---

tools/infer/utility.py
tools/program.py

use method : 
```
python3.7 tools/train.py -c xxx.yaml -o Global.use_gpu=False Global.use_xpu=True
```

support xpu for ocr

---

PPOCRLabel/gen_ocr_train_val_test.py

fix to make it work on linux/mac

fix: improper path join

---

deploy/slim/quantization/README.md
test_tipc/configs/ch_PP-OCRv2_det_PACT/train_infer_python.txt
test_tipc/configs/rec_mv3_tps_bilstm_att_v2.0/train_infer_python.txt

[tipc] fix rare trt error

---

deploy/cpp_infer/include/args.h
deploy/cpp_infer/include/ocr_rec.h
deploy/cpp_infer/readme.md
deploy/cpp_infer/readme_ch.md
deploy/cpp_infer/src/args.cpp
deploy/cpp_infer/src/ocr_rec.cpp
deploy/cpp_infer/src/paddleocr.cpp
deploy/cpp_infer/src/preprocess_op.cpp

update cpp infer for rec

---

tools/infer/utility.py

update trt dynamic shape for v3 rec

update trt dynamic shape for v3 rec

---

tools/infer/utility.py

fix svtr mkldnn

---

doc/doc_ch/algorithm_rec_sar.md
doc/doc_ch/algorithm_rec_srn.md
doc/doc_en/algorithm_rec_sar_en.md
doc/doc_en/algorithm_rec_srn_en.md

[doc] update doc for SAR and SRN

---

doc/doc_ch/algorithm_det_sast.md
doc/doc_en/algorithm_det_sast_en.md

add sast doc

---

configs/rec/PP-OCRv3/ch_PP-OCRv3_rec.yml
configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml
doc/doc_ch/knowledge_distillation.md
doc/doc_en/knowledge_distillation_en.md
ppocr/utils/utility.py

1. fix get_image_file logic becuase imagewhat may fail for web images
2. upgrade kd doc

upgrade kd doc

---

configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml

add config for en_model

---

tools/infer/utility.py

I see that many users need to show the predicted probability on the visualization, so I made a simple implementation. like this~

display probability scores on visualization 

---

doc/doc_ch/add_new_algorithm.md
doc/doc_en/add_new_algorithm_en.md
ppocr/metrics/det_metric.py
ppocr/metrics/e2e_metric.py
ppocr/metrics/kie_metric.py
ppstructure/vqa/infer_ser_e2e.py
ppstructure/vqa/train_re.py
test_tipc/docs/jeston_test_train_inference_python.md
tools/infer/predict_system.py
tools/infer/utility.py
tools/infer_cls.py
tools/infer_e2e.py

Fix some typos for Jetson, metrics and result.

Fix some typos for Jetson, metrics and result.

---

tools/infer_rec.py

fix infer rec encoding

---

deploy/hubserving/ocr_det/params.py
deploy/hubserving/ocr_rec/params.py
deploy/hubserving/ocr_system/params.py
deploy/hubserving/readme.md
deploy/hubserving/readme_en.md

update hubserving for PPOCRv3

---

PPOCRLabel/PPOCRLabel.py
PPOCRLabel/README.md
PPOCRLabel/README_ch.md

修复3个 BUG
- 没有 `difficult` 字段会导致崩溃
- KIE 模式没有 `kie_cls` 字段会导致崩溃
- KIE 修改框会出现重复的字段
请审核 @Evezerest 😄

[PPOCRLable] Fix 3 Bugs 🐛 

---

doc/doc_en/PP-OCRv3_introduction_en.md

add ppocrv3 eng

---

PPOCRLabel/PPOCRLabel.py

Fix a bug of kie as null

---

tools/infer/predict_rec.py
tools/infer/predict_system.py
tools/infer/utility.py

modified default shape

---

paddleocr.py
tools/infer/utility.py

Update rec name

---

tools/infer/predict_rec.py
tools/infer/predict_system.py
tools/infer/utility.py

Cherry pick dygraph

---

deploy/slim/quantization/README.md
deploy/slim/quantization/README_en.md
doc/doc_ch/inference_ppocr.md
doc/doc_en/inference_ppocr_en.md

update doc for v3 det quant
update doc for v3 infer

update doc for v3 det quant

---

PPOCRLabel/PPOCRLabel.py

KIE 模式下，手动标注框，并选择好 cls
使用右上方【自动标注】按钮会将所有框的 key 信息清空
@Evezerest  请审核
#6201 
#6216

[PPOCRLabel BUG] Fix re-reco will clear all key message 🐛 

---

ppocr/data/imaug/fce_targets.py

self.vector_slope 方法不存在，应该是漏掉了

the file has no  function [self.vector_slope]

---

tools/infer/utility.py

fix rec prediction for trt7

---

ppocr/modeling/architectures/__init__.py
tools/train.py

att, a demo training script is as follows.
```shell
python tools/train.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_student.yml -o Global.to_static=True Global.image_shape="[3,960,960]"
```

add support for static training

---

PPOCRLabel/PPOCRLabel.py

PR #6240 to dygraph
请审核 @Evezerest 😄

[PPOCRLabel BUG] Fix re-reco will clear all key message 🐛

---

tools/export_model.py
tools/infer_rec.py

1) update infer_rec.py
2) update export_model.py

fix some bugs

---

ppocr/modeling/architectures/__init__.py
ppocr/modeling/heads/rec_sar_head.py

add support for svtr static training

---

doc/doc_en/algorithm_rec_starnet.md

add starnet doc & test=document_fix

---

test_tipc/configs/ch_PP-OCRv3_rec_PACT/train_infer_python.txt
test_tipc/prepare.sh

fix tipc v3 rec pact model path

---

deploy/cpp_infer/CMakeLists.txt

update cpp infer for onnxruntime

update cpp infer for onnxruntime

---

tools/infer/utility.py

fix trt int8 inference

---

ppstructure/table/predict_table.py
test_tipc/common_func.sh
test_tipc/configs/ch_PP-OCRv2_det_KL/model_linux_gpu_normal_normal_infer_python_linux_gpu_cpu.txt
test_tipc/configs/ch_PP-OCRv2_rec_KL/model_linux_gpu_normal_normal_infer_python_linux_gpu_cpu.txt
test_tipc/configs/ch_PP-OCRv2_rec_PACT/train_infer_python.txt
test_tipc/configs/ch_PP-OCRv3_det_KL/model_linux_gpu_normal_normal_infer_python_linux_gpu_cpu.txt
test_tipc/configs/ch_PP-OCRv3_rec_KL/model_linux_gpu_normal_normal_infer_python_linux_gpu_cpu.txt
test_tipc/configs/ch_PP-OCRv3_rec_PACT/train_infer_python.txt
test_tipc/configs/ch_ppocr_mobile_v2.0_det_KL/model_linux_gpu_normal_normal_infer_python_linux_gpu_cpu.txt
test_tipc/configs/ch_ppocr_mobile_v2.0_det_PACT/train_infer_python.txt
test_tipc/configs/ch_ppocr_mobile_v2.0_rec_KL/model_linux_gpu_normal_normal_infer_python_linux_gpu_cpu.txt

[TIPC] add KL and PACT

---

test_tipc/configs/ch_PP-OCRv2/model_linux_gpu_normal_normal_paddle2onnx_python_linux_cpu.txt
test_tipc/configs/ch_PP-OCRv3/model_linux_gpu_normal_normal_paddle2onnx_python_linux_cpu.txt
test_tipc/configs/ch_ppocr_server_v2.0/model_linux_gpu_normal_normal_paddle2onnx_python_linux_cpu.txt
test_tipc/configs/ch_ppocr_server_v2.0_det/model_linux_gpu_normal_normal_paddle2onnx_python_linux_cpu.txt

[TIPC] fix onnx tipc long cost time

---

test_tipc/configs/ch_PP-OCRv2/model_linux_gpu_normal_normal_infer_cpp_linux_gpu_cpu.txt
test_tipc/configs/ch_PP-OCRv2_rec/model_linux_gpu_normal_normal_infer_cpp_linux_gpu_cpu.txt
test_tipc/configs/ch_ppocr_mobile_v2.0/model_linux_gpu_normal_normal_infer_cpp_linux_gpu_cpu.txt
test_tipc/configs/ch_ppocr_mobile_v2.0_rec/model_linux_gpu_normal_normal_infer_cpp_linux_gpu_cpu.txt
test_tipc/configs/ch_ppocr_server_v2.0/model_linux_gpu_normal_normal_infer_cpp_linux_gpu_cpu.txt
test_tipc/configs/ch_ppocr_server_v2.0_rec/model_linux_gpu_normal_normal_infer_cpp_linux_gpu_cpu.txt
test_tipc/prepare.sh
test_tipc/test_inference_cpp.sh

[TIPC] update_tipc_cpp_infer

---

deploy/pdserving/ocr_reader.py
deploy/pdserving/web_service.py

update pipeline to v3

---

deploy/pdserving/ocr_reader.py
deploy/pdserving/web_service.py

[Cherry pick] update python serving for v3

---

ppocr/losses/rec_aster_loss.py
ppocr/losses/table_att_loss.py
ppocr/modeling/backbones/kie_unet_sdmgr.py
ppocr/modeling/backbones/rec_resnet_fpn.py
ppocr/modeling/heads/rec_srn_head.py
ppocr/modeling/heads/self_attention.py

replace fluid to paddle

---

deploy/pdserving/README.md
deploy/pdserving/README_CN.md
deploy/pdserving/web_service.py
test_tipc/test_serving_infer_cpp.sh
test_tipc/test_serving_infer_python.sh

update for serving

---

ppocr/modeling/backbones/kie_unet_sdmgr.py
tools/export_model.py

fix export and kie backbone

---

test_tipc/configs/ch_PP-OCRv2/model_linux_gpu_normal_normal_infer_python_linux_gpu_cpu.txt
test_tipc/configs/ch_PP-OCRv3/model_linux_gpu_normal_normal_infer_python_linux_gpu_cpu.txt
test_tipc/configs/ch_PP-OCRv3_rec/ch_PP-OCRv3_rec_distillation.yml
test_tipc/configs/ch_ppocr_mobile_v2.0/model_linux_gpu_normal_normal_infer_python_linux_gpu_cpu.txt
test_tipc/configs/ch_ppocr_mobile_v2.0_det/model_linux_gpu_normal_normal_infer_python_jetson.txt
test_tipc/configs/ch_ppocr_mobile_v2.0_det/train_mac_cpu_normal_normal_infer_python_mac_cpu.txt
test_tipc/configs/ch_ppocr_mobile_v2.0_det/train_windows_gpu_normal_normal_infer_python_windows_cpu_gpu.txt
test_tipc/configs/ch_ppocr_server_v2.0/model_linux_gpu_normal_normal_infer_python_linux_gpu_cpu.txt
test_tipc/prepare.sh
test_tipc/test_inference_python.sh

[TIPC] infer_python

---

ppstructure/vqa/README.md

Just add a space to the error command

Fix OCR engine + SER command in vqa readme

---

tools/infer/predict_det.py

https://github.com/PaddlePaddle/PaddleOCR/issues/5752
https://github.com/PaddlePaddle/PaddleOCR/issues/6591

[bug fix] fix points order bug

---

ppstructure/vqa/README.md
ppstructure/vqa/README_ch.md

Fix the error path of End2End evaluation command of SER doc and OCR engine + SER + RE command

Fix SER and RE VQA docs command error

---

deploy/cpp_infer/docs/windows_vs2019_build.md

Add the onnxruntime.dll and paddle2onnx.dll to Step3.

update win doc

---

applications/包装生产日期识别.md

[add  applications]  package production data

---

doc/doc_ch/inference_ppocr.md
doc/doc_en/inference_ppocr_en.md

Fix inference doc

---

test_tipc/configs/en_table_structure/train_pact_infer_python.txt

[TIPC] Fix table pact

---

test_tipc/benchmark_train.sh
test_tipc/test_train_inference_python.sh

[tipc]fix fp16 benchmark train

---

PPOCRLabel/PPOCRLabel.py

Fixed the bug where Chinese path pictures were not recognized

Fixed Chinese path not recognize bug

---

tools/infer/predict_rec.py

重新合入spin算法，解决之前合入中predict_rec.py中的bug.

fixed predict_rec

---

test_tipc/readme.md
tools/infer/predict_rec.py

修改predict_rec.py中的bug.在test_tipc/readme.md中添加spin

spin复现合入：fixed bug for predict_rec

---

test_tipc/test_train_inference_python.sh

[TIPC] fix tipc infer log

---

test_tipc/common_func.sh
test_tipc/test_inference_cpp.sh
test_tipc/test_inference_python.sh
test_tipc/test_paddle2onnx.sh
test_tipc/test_ptq_inference_python.sh
test_tipc/test_serving_infer_cpp.sh
test_tipc/test_serving_infer_python.sh
test_tipc/test_train_inference_python.sh

add log_path in result.log

---

tools/export_model.py

rever rec input h

---

tools/infer/utility.py

att
Almost no diff using collecting shape
* GPU
* [2022/08/17 15:19:19] ppocr INFO: Predicts of ./train_data/test_eval/200_crop/310_crop_160_16.jpg:('出发地陶克苏', 0.798431932926178)
* GPU+trt + delete pass
* [2022/08/17 15:20:21] ppocr INFO: Predicts of ./train_data/test_eval/200_crop/310_crop_160_16.jpg:('出发地陶克苏', 0.7984303832054138)
* GPU + trt + collect shape
* [2022/08/17 15:21:48] ppocr INFO: Predicts of ./train_data/test_eval/200_crop/310_crop_160_16.jpg:('出发地陶克苏', 0.7984321713447571)

rm dyg shape for trt

---

tools/infer_sr.py
tools/program.py

fix sr typo

---

doc/doc_ch/algorithm_rec_srn.md
tools/infer/predict_rec.py

Fix infer rec

---

ppocr/data/imaug/label_ops.py

fix nlp return token_type_ids

---

tools/infer/utility.py
tools/infer_kie_token_ser_re.py

fix re bug

---

doc/doc_ch/algorithm_rec_srn.md
tools/infer/predict_rec.py

fix infer_rec for other input

---

ppocr/modeling/backbones/vqa_layoutlm.py

fix vi name

---

ppstructure/layout/README.md
ppstructure/layout/README_ch.md
ppstructure/recovery/README.md
ppstructure/recovery/README_ch.md

【cp】add quickstart

---

applications/发票关键信息抽取.md
ppstructure/kie/README.md
ppstructure/kie/README_ch.md

fix doc bug

---

test_tipc/prepare.sh

fix cv2 req

---

PPOCRLabel/README.md
PPOCRLabel/README_ch.md

Update the README of PPOCRLabel

Update the README of PPOCRLabel

---

paddleocr.py

支持传入 bytes 类型以应对更多使用场景
```python
ocr = PaddleOCR(lang='ch')
with open('image.jpg', mode='rb') as file:
...
res = ocr.ocr(file.read())
container: BytesIO = screenshot()
res = ocr.ocr(container.getvalue())
```

update bytes support

---

PPOCRLabel/PPOCRLabel.py
configs/table/SLANet_ch.yml

更新了配置文件中 Eval 部分 data_dir 前多余的空格。

更新配置文件(SLANet_ch.yml) 与PPOCRLabel相关问题。

---

test_tipc/test_paddle2onnx.sh

tipc paddle2onnx trans for newest paddle2onnx 1.0.0

tipc paddle2onnx trans

---

configs/rec/rec_resnet_stn_bilstm_att.yml
doc/doc_ch/algorithm_rec_seed.md
doc/doc_en/algorithm_rec_seed_en.md
ppocr/modeling/heads/rec_aster_head.py
ppocr/postprocess/rec_postprocess.py
tools/export_model.py
tools/infer/predict_rec.py
tools/infer_rec.py

Fix seed export

---

deploy/cpp_infer/include/args.h
deploy/cpp_infer/include/paddlestructure.h
deploy/cpp_infer/include/postprocess_op.h
deploy/cpp_infer/include/structure_table.h
deploy/cpp_infer/include/utility.h
deploy/cpp_infer/readme.md
deploy/cpp_infer/readme_ch.md
deploy/cpp_infer/src/args.cpp
deploy/cpp_infer/src/main.cpp
deploy/cpp_infer/src/paddlestructure.cpp
deploy/cpp_infer/src/postprocess_op.cpp
deploy/cpp_infer/src/structure_table.cpp
deploy/cpp_infer/src/utility.cpp
ppstructure/utility.py

1. add merge_no_span_structure to cpp_infer
2. add table vis like

 fix table cpp infer bug

---

deploy/cpp_infer/src/ocr_cls.cpp
deploy/cpp_infer/src/ocr_det.cpp
deploy/cpp_infer/src/ocr_rec.cpp
deploy/lite/config.txt
deploy/lite/readme.md
deploy/lite/readme_ch.md
deploy/slim/quantization/README.md
deploy/slim/quantization/README_en.md
tools/infer/utility.py

- update slim/quant/readme to PPOCRv3 version
- update deploy/lite/readme to PPOCRv3 version
- support cpp_infer auto dynamic shape when trt enabled

support ppocrv3 for lite deploy readme

---

deploy/cpp_infer/src/ocr_cls.cpp
deploy/cpp_infer/src/ocr_det.cpp
deploy/cpp_infer/src/ocr_rec.cpp
deploy/lite/config.txt
deploy/lite/readme.md
deploy/lite/readme_ch.md
deploy/slim/quantization/README.md
deploy/slim/quantization/README_en.md
tools/infer/utility.py

- update slim/quant/readme to PPOCRv3 version
- update deploy/lite/readme to PPOCRv3 version
- support cpp_infer auto dynamic shape when trt enabled

add ppocrv3 for lite deploy readme

---

configs/rec/PP-OCRv3/ch_PP-OCRv3_rec.yml
configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml
configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml

exposure `max_text_length` for recconaug

[CP]exposure params for recconaug

---

configs/rec/PP-OCRv3/ch_PP-OCRv3_rec.yml
configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml
configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml

exposure `max_text_length` for recconaug

exposure params for recconaug

---

applications/扫描合同关键信息提取.md

[cherry-pick] 扫描合同关键信息抽取

---

applications/扫描合同关键信息提取.md

[Application] 扫描合同关键信息提取

---

applications/中文表格识别.md
ppstructure/table/README.md
ppstructure/table/README_ch.md

cp https://github.com/PaddlePaddle/PaddleOCR/pull/7714

cp of 7714 

---

paddleocr.py

Prevent download when using onnx model file.

fix #7534 (Prevent download when using onnx model file)

---

ppocr/modeling/backbones/rec_efficientb3_pren.py
ppocr/postprocess/rec_postprocess.py
tools/export_model.py
tools/infer/predict_rec.py

att, fix export and predict for PREN([PR link](https://github.com/PaddlePaddle/PaddleOCR/pull/5563/files))
* infer
```bash
python tools/infer_rec.py -c configs/rec/rec_efficientb3_fpn_pren.yml
```
* export
```bash
python tools/export_model.py  -c configs/rec/rec_efficientb3_fpn_pren.yml
```
* predict
```bash
python3 tools/infer/predict_rec.py --image_dir='./doc/imgs_words_en/word_10.png' --rec_model_dir=./pren_infer/ --rec_algorithm='PREN' --rec_image_shape='3,64,256' --rec_char_dict_path='./ppocr/utils/ic15_dict.txt' --use_space_char=False
```

fix PREN export and infer

---

deploy/hubserving/kie_ser/__init__.py
deploy/hubserving/kie_ser/config.json
deploy/hubserving/kie_ser/module.py
deploy/hubserving/kie_ser/params.py
deploy/hubserving/kie_ser_re/__init__.py
deploy/hubserving/kie_ser_re/config.json
deploy/hubserving/kie_ser_re/module.py
deploy/hubserving/kie_ser_re/params.py
deploy/hubserving/readme.md
deploy/hubserving/readme_en.md
ppocr/data/imaug/label_ops.py
ppstructure/kie/predict_kie_token_ser_re.py

add ser+re hub serving

---

deploy/paddle2onnx/readme.md

updata paddle2onnx en doc

---

deploy/paddle2onnx/readme.md

cherry-pick #7855 to release/2.6

[cherry-pick] update paddle2onnx

---

ppocr/data/lmdb_dataset.py

support reconaug

---

paddleocr.py

fix whl for layout recovery

---

doc/doc_en/inference_ppocr_en.md

[doc] fix wrong model name

---

configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh_udml.yml

fix hidden state for ser

---

deploy/cpp_infer/readme.md
deploy/pdserving/README.md
doc/doc_en/ppocr_introduction_en.md
doc/doc_en/recognition_en.md

Fixed some broken links

---

doc/doc_ch/algorithm_rec_visionlan.md
doc/doc_en/algorithm_rec_visionlan_en.md
ppocr/data/imaug/label_ops.py
ppocr/postprocess/rec_postprocess.py

fix issue https://github.com/PaddlePaddle/PaddleOCR/issues/7925

fix visionlan default dict

---

doc/doc_ch/algorithm_overview.md
doc/doc_ch/algorithm_rec_visionlan.md
doc/doc_en/algorithm_overview_en.md
doc/doc_en/algorithm_rec_visionlan_en.md
ppocr/data/imaug/label_ops.py
ppocr/postprocess/rec_postprocess.py

cp https://github.com/PaddlePaddle/PaddleOCR/pull/7989

[CP]update visionlan

---

doc/doc_ch/kie.md
doc/doc_en/kie_en.md

cp of https://github.com/PaddlePaddle/PaddleOCR/pull/8122

CP of 8112

---

ppocr/data/imaug/label_ops.py

rm visionlan invalid params

---

ppocr/data/imaug/label_ops.py

cp https://github.com/PaddlePaddle/PaddleOCR/pull/8128

[CP] rm visionlan invalid params

---

test_tipc/test_serving_infer_cpp.sh

fix serving stop

---

doc/doc_ch/finetune.md

fix finetune

---

ppstructure/predict_system.py
ppstructure/recovery/recovery_to_doc.py
ppstructure/recovery/requirements.txt
ppstructure/recovery/table_process.py
requirements.txt

1、修复bug：删除1.docx保存
2、2种类型docx保存，修改不同的命名
3、删除recovery requirement.txt的PyMupdf
4、更新requirement.txt安装版本

optimize recovery

---

PPOCRLabel/PPOCRLabel.py
PPOCRLabel/libs/autoDialog.py
PPOCRLabel/libs/canvas.py

Modify the output bug of PaddleOCR==2.6.1 update.
修改PaddleOCR==2.6.1更新造成的输出维度bug

Modify the output bug of PaddleOCR==2.6.1 update.

---

doc/doc_ch/finetune.md
doc/doc_en/detection_en.md
doc/doc_en/finetune_en.md
doc/doc_en/recognition_en.md

[doc] add finetune en doc

---

ppocr/losses/rec_aster_loss.py

fix aster loss for axis

---

requirements.txt

cp of https://github.com/PaddlePaddle/PaddleOCR/pull/8771

fixed opencv version

---

doc/doc_ch/finetune.md
doc/doc_en/finetune_en.md

update finetune doc

---

tools/infer/predict_det.py
tools/infer/predict_rec.py

fix onnx for dynamic shape

---

doc/doc_en/quickstart_en.md
ppstructure/docs/quickstart_en.md
ppstructure/kie/README.md

@Evezerest I have cherry-picked the 3 commits from release/2.6 to dygraph branch as you asked. Please review.
Thanks, and best,
Dhruv

Cherry-pick 3 commits from release/2.6 to dygraph

---

doc/doc_ch/algorithm_overview.md
doc/doc_en/algorithm_overview_en.md

add CT to algorithm overview doc

add CT to algorithm overview

---

configs/rec/PP-OCRv3/ch_PP-OCRv3_rec.yml
configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml
configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml
configs/rec/PP-OCRv3/multi_language/arabic_PP-OCRv3_rec.yml
configs/rec/PP-OCRv3/multi_language/chinese_cht_PP-OCRv3_rec.yml
configs/rec/PP-OCRv3/multi_language/cyrillic_PP-OCRv3_rec.yml
configs/rec/PP-OCRv3/multi_language/devanagari_PP-OCRv3_rec.yml
configs/rec/PP-OCRv3/multi_language/japan_PP-OCRv3_rec.yml
configs/rec/PP-OCRv3/multi_language/ka_PP-OCRv3_rec.yml
configs/rec/PP-OCRv3/multi_language/korean_PP-OCRv3_rec.yml
configs/rec/PP-OCRv3/multi_language/latin_PP-OCRv3_rec.yml
configs/rec/PP-OCRv3/multi_language/ta_PP-OCRv3_rec.yml
configs/rec/PP-OCRv3/multi_language/te_PP-OCRv3_rec.yml
ppocr/modeling/architectures/__init__.py
tools/eval.py
tools/export_model.py
tools/program.py

rename PP-OCRv3 algorithm to SVTR_LCNet

---

test_tipc/configs/ch_PP-OCRv3_rec/ch_PP-OCRv3_rec_distillation.yml

[cherry-pick]rename tipc svtr name

---

test_tipc/configs/ch_PP-OCRv3_rec/ch_PP-OCRv3_rec_distillation.yml

rename tipc svtr name

---

ppocr/data/imaug/rec_img_aug.py

rever 'limit maximum resizing ratio'

---

tools/program.py

update is_compiled_with_npu to is_compiled_with_custim_device("npu")
Linked to https://github.com/PaddlePaddle/Paddle/pull/52385

[npu] Update npu api

---

tools/infer/utility.py

update enable_npu() api to enable_custom_device('npu') to adapt changes on Paddle

update npu inference api

---

ppocr/modeling/heads/rec_sar_head.py

fix data type error when training with fp16 and DynamicToStatic

fix data type error when training with fp16 and DynamicToStatic

---

configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_student.yml
configs/rec/PP-OCRv4/ch_PP-OCRv4_rec.yml
ppocr/modeling/backbones/__init__.py
ppocr/modeling/backbones/rec_lcnetv3.py

update PPLCNetV3 name

---

configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_student.yml
configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_teacher.yml

add v4 det pretrain link

---

configs/rec/PP-OCRv4/ch_PP-OCRv4_rec.yml
configs/rec/PP-OCRv4/ch_PP-OCRv4_rec_hgnet.yml
ppocr/data/__init__.py
ppocr/data/imaug/__init__.py
ppocr/data/imaug/rec_img_aug.py
ppocr/data/multi_scale_sampler.py
ppocr/data/simple_dataset.py

support mutli-scale training for rec model

Multi scale

---

configs/rec/PP-OCRv4/ch_PP-OCRv4_rec.yml
configs/rec/PP-OCRv4/ch_PP-OCRv4_rec_hgnet.yml
ppocr/data/imaug/__init__.py

revert eval mode

---

ppocr/modeling/heads/sr_rensnet_transformer.py
ppocr/modeling/transforms/tbsrn.py
tools/export_model.py

fix sr_telescope

---

ppocr/modeling/transforms/tbsrn.py

add dtype param for arange API.

add dtype param for arange API.

---

ppocr/utils/profiler.py
test_tipc/benchmark_train.sh

【benchmark】fix new profiler
cmd:
python tools/train.py ...
--profiler_options="batch_range=[10,20];state=GPU;tracer_option=Default;profile_path=model.profile;timer_only=True"
python tools/train.py ...
--profiler_options="batch_range=[10,20];state=GPU;tracer_option=Default;profile_path=model.profile;timer_only=False"

【benchmark】fix new profiler 

---

doc/doc_en/algorithm_overview_en.md

Fix links to super-resolution algorithm docs

[Docs] Fix links to super-resolution algorithm tutorials

---

doc/doc_ch/quickstart.md
doc/doc_en/quickstart_en.md

Add “use PaddleOCR with docker” content.

update quickstart doc

---

ppocr/optimizer/optimizer.py
test_tipc/supplementary/data_loader.py
test_tipc/supplementary/train.py
tools/eval.py
tools/infer/utility.py

clear fluid

---

paddleocr.py

cherry-pick package compatibility PR #10052

Improve package import compatibility

---

doc/doc_en/inference_args_en.md

English documentation for GH-10217

OCR preprocessing parameters documentation

---

tools/program.py

Suppress Scalar Warnings

---

tools/program.py

Suppress scalar warnings (#10509)

---

README_ch.md
configs/rec/PP-OCRv4/en_PP-OCRv4_rec.yml
doc/doc_ch/models_list.md
doc/doc_ch/quickstart.md
paddleocr.py

upload paddleocr whl to pypi

---

tools/train.py

Fix seed passing issue of build_dataloader.

Fix seed passing issue of build_dataloader

---

deploy/cpp_infer/include/paddleocr.h
deploy/cpp_infer/include/paddlestructure.h
deploy/cpp_infer/src/main.cpp
deploy/cpp_infer/src/ocr_cls.cpp
deploy/cpp_infer/src/ocr_rec.cpp
deploy/cpp_infer/src/paddleocr.cpp
deploy/cpp_infer/src/paddlestructure.cpp

* update: Using smart pointers instead of raw pointers
* update: Usinig intuitive initialization of duration

[Cherry-pick] #10441 #10512

---

requirements.txt

Update requirements.txt to add missing pyyaml library

---

ppocr/modeling/backbones/vqa_layoutlm.py

Update vqa to use the updated LayoutLM syntax from PaddleNLP

Update VQA to use the updated LayoutLM syntax from PaddleNLP

---

ppocr/utils/utility.py

…ile (#10181)
* Fix fitz camelCase deprecation and .PDF not being recognized as pdf file
* refactor get_image_file_list function

Cherrypicking GH-10181 to PaddleOCR:release/2.7

---

ppocr/data/imaug/label_ops.py
ppocr/data/pubtab_dataset.py
ppocr/data/simple_dataset.py
ppocr/postprocess/rec_postprocess.py
ppocr/postprocess/table_postprocess.py

add encoding for open

---

ppocr/losses/distillation_loss.py

fix numpy speed

---

configs/rec/rec_r45_abinet.yml
ppocr/modeling/heads/rec_abinet_head.py

rec_r45_abinet.yml add max_length and image_size

---

ppocr/modeling/heads/rec_robustscanner_head.py

rm fluid for paddle dev

---

ppocr/modeling/heads/rec_cppd_head.py

fix import collection for py310

---

test_tipc/test_train_inference_python_npu.sh
test_tipc/test_train_inference_python_xpu.sh

Others
Others
在NPU、XPU TIPC脚本中将ch_ppocr_mobile_v2_0_rec_FPGM的use_gpu默认值从true改为false，解决该模型报错的问题。
- [ ✓] 这个 PR 是提交到dygraph分支或者是一个cherry-pick，否则请先提交到dygarph分支。
- [ ✓] 这个PR清楚描述了功能，帮助评审能提升效率。This PR have fully described what it does such that reviewers can speedup.
- [ ✓] 这个PR已经经过本地测试。This PR can be convered by current tests or already test locally by you.

[TIPC]update tipc scripts

---

ppocr/modeling/heads/rec_parseq_head.py

Bug fixes
Models
normalize the output of parseq

[BugFix]Fix parseq net

---

tools/program.py

Bug fixes
Others
给非cuda设备开一个分支，不打印内存使用状况

Fix bug when running on XPU

---

ppocr/postprocess/rec_postprocess.py

Bug fixes
Others
Fix a bug during rec_r45_visionlan model evaluation.

fix a bug for rec_postprocess.py

---

doc/doc_ch/algorithm_overview.md
doc/doc_ch/algorithm_rec-satrn.md
doc/doc_en/algorithm_overview_en.md
doc/doc_en/algorithm_rec_satrn_en.md

Docs
Docs
飞桨套件快乐开源常规赛-补充Satrn识别模型文档

doc: add doc for satrn

---

README.md

update paddlex of readme for 2.7.1

---

README.md

Modify readme 27

---

README.md

update paddlex of readme

---

applications/README.md
applications/包装生产日期识别.md
applications/印章弯曲文字识别.md
applications/扫描合同关键信息提取.md

Others
Docs
rm QR code in document

rm QR code in the document

---

applications/PCB字符识别/PCB字符识别.md
applications/光功率计数码管字符识别/光功率计数码管字符识别.md
applications/包装生产日期识别.md
applications/发票关键信息抽取.md
applications/多模态表单识别.md
applications/手写文字识别.md
applications/液晶屏读数识别.md
applications/轻量级车牌识别.md
applications/高精度中文识别模型.md

rm QR code

---

doc/doc_en/recognition_en.md

Bug fixes
Docs
Fix dead links in recognition_en documentation.

Fix dead links

---

.pre-commit-config.yaml
ppocr/utils/utility.py
ppstructure/pdf2word/pdf2word.py
requirements.txt

cherry-pick for lazy import pymupdf and pre-commit

---

ppocr/modeling/heads/rec_sar_head.py
ppocr/modeling/heads/self_attention.py
ppocr/modeling/transforms/tps.py

Bug fixes
Others
adapter new type promotion rule for Paddle 2.6

adapter new type promotion rule for Paddle 2.6

---

deploy/cpp_infer/docs/windows_vs2019_build.md
deploy/cpp_infer/readme.md
deploy/cpp_infer/readme_ch.md
test_tipc/docs/install.md

this PR correct links mentioned at #11763
By the way, it's worth to thoroughly review the relevant docs.

update link mentioned at #11763

---

StyleText/engine/text_drawers.py

Others
Others
cherry-pick
- #11556

fix AttributeError

---

paddleocr.py
ppocr/utils/utility.py
ppstructure/pdf2word/pdf2word.py

cherry-pick #11820 and bump version to 2.7.3

Prepare 2.7.3 release

---

paddleocr.py

TextSystem is imported correctly in paddleocr.py

---

configs/rec/rec_vit_parseq.yml

Bug fixes
Models
补充模型配置rec_vit_parseq.yml中train 和 eval 的data_dir字段

update  rec_vit_parseq.yml, test=document_fix

---

setup.py

change the version information from "VERSION = 2.8.0" to "2.8.0"

fix weird version info

---

doc/doc_ch/quickstart.md
doc/doc_ch/slice.md
doc/doc_en/quickstart_en.md

- very large image
- result
- https://github.com/PaddlePaddle/PaddleOCR/pull/12152

add `slice` op demo for quickstart

---

README.md

【Doc】Add notification document

---

README.md
README_en.md

docs(README): Add Discord shields

---

tools/infer/utility.py

添加{"cudnn_conv_algo_search": "DEFAULT"}参数，加速gpu下onnxruntime推理速度；指定"CPUExecutionProvider"参数解决cpu环境下onnxruntime报错。

解决onnruntime推理问题

---

ppocr/modeling/backbones/det_mobilenet_v3.py
ppocr/modeling/backbones/rec_hgnet.py
ppocr/modeling/backbones/rec_lcnetv3.py

fix npu bug for AdaptiveAvgPool2D

fix npu bug for AdaptiveAvgPool2D

---

__init__.py
paddleocr.py

fix layout recovery import error

---

.github/ISSUE_TEMPLATE/bug-report.yml

chore: Update bug report template

---

deploy/fastdeploy/serving/fastdeploy_serving/models/det_postprocess/1/model.py

fix: 'numpy' has no attribute 'astype'

---

.github/ISSUE_TEMPLATE/bug-report.yml

由于观察到小伙伴们提问issue，仍然会丢失关键的运行环境和复现代码信息，本RP将这两个字段改为必填项，提高效率

chore(Issue_template): Add validation of Environment and MPE code

---

.pre-commit-config.yaml
configs/det/det_repsvtr_db.yml
configs/rec/SVTRv2/rec_repsvtr_ch.yml
configs/rec/SVTRv2/rec_svtrv2_ch.yml
configs/rec/SVTRv2/rec_svtrv2_ch_distillation.yml
ppocr/modeling/backbones/__init__.py
ppocr/modeling/backbones/rec_repvit.py
ppocr/modeling/backbones/rec_svtrv2.py
ppocr/modeling/heads/rec_multi_head.py
tools/train.py

add SVTRv2 to the release2.6.1 branch

support PaddleX for SVTRv2

---

tools/infer/utility.py

support mlu for infer

---

.github/ISSUE_TEMPLATE/bug-report.yml

issue template添加中文描述，去掉多余问题，更加直观，提高效率

chore: Update issue template

---

ppocr/modeling/heads/table_att_head.py

Fix pir dy2st train

---

paddleocr.py
tools/infer/utility.py

fix
- https://github.com/PaddlePaddle/PaddleOCR/pull/13896#issuecomment-2378523045

fix hubserving run error

---

tools/naive_sync_bn.py
tools/train.py

[NPU] support sybn for npu

---

tools/naive_sync_bn.py
tools/train.py

[NPU] cherrypick13983

---

ppocr/modeling/heads/det_db_head.py

fix nan in PP-OCRv4 for fp16 train

fix nan in PP-OCRv4

---

configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_student.yml
configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_teacher.yml
ppocr/modeling/heads/det_db_head.py

fix nan in ppocrv4 for benchmark

fix nan in ppocrv4 for benchmark

---

.github/workflows/build_publish_develop_docs.yml

尝试添加基于分支的文档更新支持，需要merge进去看看能否生效

ci: Support seperate update of branch docs

---

.github/workflows/build_publish_develop_docs.yml

ci: add branch update document strategy

---

docs/quick_start.en.md
docs/quick_start.md

docs: add command line usage documentation of quickstart page

---

docs/quick_start.en.md
docs/quick_start.md

快速开始添加安装Paddle框架的文档，相关issue #14115

docs: add installation documentation of paddle

---

docs/quick_start.en.md
docs/quick_start.md

docs: fixed typo

---

paddleocr.py

image without any text will show a warning

---

ppstructure/kie/predict_kie_token_ser.py
tools/infer/utility.py

@ZeyuChen 这个模型的inputs有4个，但原代码中使用onnx推理时仅使用了1个，在推理时会报错。
本次PR修改input为4个，并兼容了paddleInfer和onnx输出的output获取方式。
issue请参阅:
- #14107

[third-party] Fix the issue of inference errors with KE models in ONNX format

---

docs/applications/overview.md

完善场景应用部分文档，添加说明，表明此部分文档有些out of date，谨慎选择使用。

docs: add warning of Apolications part

---

ppocr/data/imaug/pg_process.py

修改求min_area_quad的左右边界中心点的代码，之前的代码有点问题。

fix:calcute the left_center_pt and right_center_pt from min_area_quad

---

ppocr/modeling/heads/rec_sar_head.py

修改w的type，从而兼容paddle3.0b2和paddle develop 版本

repair type bug for ppocrv3

---

ppocr/modeling/heads/det_db_head.py

fix_server_v4_det_output

---

deploy/cpp_infer/include/utility.h
deploy/cpp_infer/src/clipper.cpp
deploy/cpp_infer/src/main.cpp
deploy/cpp_infer/src/ocr_cls.cpp
deploy/cpp_infer/src/ocr_rec.cpp
deploy/cpp_infer/src/paddleocr.cpp
deploy/cpp_infer/src/paddlestructure.cpp
deploy/cpp_infer/src/postprocess_op.cpp
deploy/cpp_infer/src/preprocess_op.cpp
deploy/cpp_infer/src/structure_layout.cpp
deploy/cpp_infer/src/structure_table.cpp
deploy/cpp_infer/src/utility.cpp

CPP: codes view and some minimum fix (compiler warning...)

---

deploy/cpp_infer/src/utility.cpp

CPP: Using vector initialize list constructor

---

docs/quick_start.en.md
paddleocr.py

allow environment variable for BASE_DIR models

---

docs/infer_deploy/paddle2onnx.en.md
docs/infer_deploy/paddle2onnx.md

This pull request includes multiple changes to the documentation files for PaddleOCR model conversion and prediction. The changes mainly focus on updating the instructions for converting PaddleOCR models to ONNX models, adding new sections, and correcting file paths.
* [`docs/infer_deploy/paddle2onnx.en.md`](diffhunk://#diff-bb908ec2fe2ac9480f4d92a1580acb567e2bc3747ff06a8def1805a8bc516386L10-R10): Added a link to an online AI Studio project for convenience.
* [`docs/infer_deploy/paddle2onnx.en.md`](diffhunk://#diff-bb908ec2fe2ac9480f4d92a1580acb567e2bc3747ff06a8def1805a8bc516386L27-R27): Updated the supported ONNX Opset versions from 9~18 to 7~19.
* [`docs/infer_deploy/paddle2onnx.en.md`](diffhunk://#diff-bb908ec2fe2ac9480f4d92a1580acb567e2bc3747ff06a8def1805a8bc516386L43-R50): Changed …

docs: update paddle2onnx docs

---

tools/infer/utility.py

[GCU] Update gcu config

---

tools/infer/utility.py

update gcu config
cherry-pick from https://github.com/PaddlePaddle/PaddleOCR/pull/14851

[cherry-pick][GCU] Update gcu config (#14851)

---

paddleocr.py

同 #8275
针对误用参数及早报错并根据参数跳过无需执行的代码

PaddleOCR.ocr: 去除不必要的方法调用

---

docs/version3.x/other_devices_support/multi_devices_use_guide.en.md
docs/version3.x/other_devices_support/multi_devices_use_guide.md
docs/version3.x/other_devices_support/paddlepaddle_install_NPU.en.md
docs/version3.x/other_devices_support/paddlepaddle_install_NPU.md
docs/version3.x/other_devices_support/paddlepaddle_install_XPU.en.md
docs/version3.x/other_devices_support/paddlepaddle_install_XPU.md

add multi devices use guide

---

docs/version3.x/other_devices_support/multi_devices_use_guide.en.md
docs/version3.x/other_devices_support/multi_devices_use_guide.md

modify multi-device use guide

---

README.md
README_en.md

update README (#15274)

---

docs/quick_start.en.md
docs/quick_start.md
docs/version3.x/pipeline_usage/OCR.en.md
docs/version3.x/pipeline_usage/OCR.md

* Add example for switching to server models
* Add examples in quickstart

[Cherry-pick][Docs] Add example for switching to server models (#15320)

---

docs/version3.x/other_devices_support/paddlepaddle_install_NPU.en.md
docs/version3.x/other_devices_support/paddlepaddle_install_NPU.md

modify npu install docs

---

docs/version3.x/module_usage/doc_img_orientation_classification.en.md
docs/version3.x/module_usage/doc_img_orientation_classification.md
docs/version3.x/module_usage/doc_vlm.en.md
docs/version3.x/module_usage/doc_vlm.md
docs/version3.x/module_usage/formula_recognition.en.md
docs/version3.x/module_usage/formula_recognition.md
docs/version3.x/module_usage/layout_detection.en.md
docs/version3.x/module_usage/layout_detection.md
docs/version3.x/module_usage/seal_text_detection.en.md
docs/version3.x/module_usage/seal_text_detection.md
docs/version3.x/module_usage/table_cells_detection.en.md
docs/version3.x/module_usage/table_cells_detection.md
docs/version3.x/module_usage/table_classification.en.md
docs/version3.x/module_usage/table_classification.md
docs/version3.x/module_usage/table_structure_recognition.en.md
docs/version3.x/module_usage/table_structure_recognition.md
docs/version3.x/module_usage/text_detection.en.md
docs/version3.x/module_usage/text_detection.md
docs/version3.x/module_usage/text_image_unwarping.en.md
docs/version3.x/module_usage/text_image_unwarping.md
docs/version3.x/module_usage/text_line_orientation_classification.en.md
docs/version3.x/module_usage/text_line_orientation_classification.md
docs/version3.x/module_usage/text_recognition.en.md
docs/version3.x/module_usage/text_recognition.md

* fix email for all commit
* update mkldnn default value and description
* fix docs en description

update api and doc (#15378)

---

docs/version3.x/module_usage/textline_orientation_classification.en.md
docs/version3.x/module_usage/textline_orientation_classification.md
docs/version3.x/pipeline_usage/OCR.en.md
docs/version3.x/pipeline_usage/OCR.md
docs/version3.x/pipeline_usage/PP-ChatOCRv4.en.md
docs/version3.x/pipeline_usage/PP-ChatOCRv4.md
docs/version3.x/pipeline_usage/PP-StructureV3.md
docs/version3.x/pipeline_usage/table_recognition_v2.en.md
docs/version3.x/pipeline_usage/table_recognition_v2.md
mkdocs.yml
paddleocr/_models/__init__.py
paddleocr/_models/textline_orientation_classification.py
paddleocr/_pipelines/doc_preprocessor.py
paddleocr/_pipelines/ocr.py
paddleocr/_pipelines/pp_chatocrv4_doc.py
paddleocr/_pipelines/pp_structurev3.py
paddleocr/_pipelines/seal_recognition.py
paddleocr/_pipelines/table_recognition_v2.py
paddleocr/_utils/cli.py
tests/predictors/test_textline_orientation_classifcation.py

* Support textline_orientation for chatocr and unify naming of textline orientation
* Unify description
* Update documentation
* Fix serving doc

[Cherry-pick][Feat] Support `textline_orientation` for chatocr and unify naming of text line orientation (#15337)

---

docs/FAQ.md

This small PR fixes the issues in the FAQ.

fix docs faq

---

docs/datasets/table_datasets.en.md
docs/datasets/table_datasets.md

This small PR fixes the `pubtab_dataset.py` reference in docs.

Update pubtab dataset script reference

---

docs/version3.x/pipeline_usage/OCR.en.md
docs/version3.x/pipeline_usage/OCR.md
docs/version3.x/pipeline_usage/PP-ChatOCRv4.en.md
docs/version3.x/pipeline_usage/PP-ChatOCRv4.md
docs/version3.x/pipeline_usage/PP-StructureV3.en.md
docs/version3.x/pipeline_usage/PP-StructureV3.md
docs/version3.x/pipeline_usage/doc_preprocessor.en.md
docs/version3.x/pipeline_usage/doc_preprocessor.md
docs/version3.x/pipeline_usage/formula_recognition.en.md
docs/version3.x/pipeline_usage/formula_recognition.md
docs/version3.x/pipeline_usage/seal_recognition.en.md
docs/version3.x/pipeline_usage/seal_recognition.md
docs/version3.x/pipeline_usage/table_recognition_v2.en.md
docs/version3.x/pipeline_usage/table_recognition_v2.md

This reverts commit 3e7047d95a408855cfaaf8a472a2fb365323eb87.

Revert "add visualize parameter (#15854)"
