- ppocr/modeling/architectures/rec_model.py
- ppocr/postprocess/db_postprocess.py
- tools/export_model.py
- tools/infer/predict_det.py
- tools/infer/predict_eval.py
- tools/infer/utility.py
- visualize predict results, for example
> add visualize code

- configs/rec/rec_icdar15_train.yml
- doc/recognition.md
- ppocr/data/rec/dataset_traversal.py
- ppocr/utils/character.py
* add rec doc
* rename output dir
> Fix inference

- configs/det/det_db_mv3.yml
- ppocr/data/det/dataset_traversal.py
- tools/infer/predict_det.py
- tools/infer/utility.py
- tools/infer_det.py
- solve detection inference problem 
- solve visualized problem when running detection inference
> valid det inference

- configs/det/det_db_icdar15_reader.yml
- configs/det/det_east_icdar15_reader.yml
- configs/rec/rec_benchmark_reader.yml
- doc/detection.md
- ppocr/data/det/dataset_traversal.py
- tools/eval.py
- tools/eval_utils/eval_det_utils.py
- tools/infer_det.py
- single_img_path to infer_img as rec model
- fix det eval bug
> single_img_path to infer_img as rec model, fix eval Hmean=0

- README.md
- README_en.md
- ppocr/modeling/architectures/det_model.py
- tools/eval.py
- tools/export_model.py
- tools/infer/predict_det.py
- tools/infer/predict_rec.py
- tools/infer/predict_system.py
- tools/infer_det.py
- tools/infer_rec.py
- tools/train.py
- discard export PYTHONPATH manually
- fix issue #206
> discard export PYTHONPATH manually and fix east label map dynamic shape

- configs/rec/rec_icdar15_train.yml
- tools/program.py
- tools/train.py
+-----+------------------+--------------+--------------+--------+---------+
| No. |             TYPE |        INPUT |       OUTPUT | PARAMs |   FLOPs |
+-----+------------------+--------------+--------------+--------+---------+
|   0 |           conv2d | (3, 32, 100) |  (8, 16, 50) |    216 |  345600 |
|   1 |       batch_norm |  (8, 16, 50) |  (8, 16, 50) |     16 |   12800 |
|   2 |           conv2d |  (8, 16, 50) |  (8, 16, 50) |     64 |  102400 |
|   3 |       batch_norm |  (8, 16, 50) |  (8, 16, 50) |     16 |   12800 |
|   4 |             relu |  (8, 16, 50) |  (8, 16, 50) |      0 |   -6400 |
|   5 | depthwise_conv2d |  (8, 16, 50) |  (8, 16, 50) |      9 |   14400 |
|   6 |       batch_norm |  (8, 16, 50) |  (8, 16, 50) |     16 |   12800 |
|   7 |             relu |  (8, 16, 50) …
> dump model structure

- doc/doc_ch/installation.md
- doc/doc_en/installation_en.md
> Add CUDNN version information

- deploy/cpp_infer/include/config.h
- deploy/cpp_infer/include/ocr_det.h
- deploy/cpp_infer/include/ocr_rec.h
- deploy/cpp_infer/src/main.cpp
- deploy/cpp_infer/src/ocr_det.cpp
- deploy/cpp_infer/src/ocr_rec.cpp
- deploy/cpp_infer/tools/config.txt
- tools/infer/predict_det.py
- tools/infer/predict_rec.py
- tools/infer/utility.py
There is not memory leak for mkldnn in Paddle1.8.4(or later) for predictor.run()
> replace zero_copy_run to run for memory leak

- deploy/lite/db_post_process.cc
这个bug会使db_post_process.cc中的Uclip函数中的points为空，从而在使用minAreaRect(points)时发送崩溃
> fix lite crash bug

- ppocr/modeling/architectures/rec_model.py
环境: docker hub上的paddlepaddle/paddle:latest-gpu-cuda10.1-cudnn7镜像（注意: 该镜像是python3.5）
问题: python3.6之前的dict类是无序的，导致tools/program.py文件中build函数里的fetch_name_list是无序的
造成现象: 验证时取得的preds可能是softmax后的分布结果，而不是decode后的结果，致使验证准确率计算不正确，影响训练和验证脚本。
我只使用了字符识别的代码，所以其他部分在python3.6以下的版本可能也会出现相关的问题，需要开发者审核一下。
建议: 使用OrderedDict代替dict。
> 因Python3.6以前的字典类型是无序的而导致的错误

- ppocr/utils/stats.py
- tools/program.py
样例
```bash
[2020/11/16 11:11:18] root INFO: During the training process, after the 0th iteration, an evaluation is run every 1171 iterations
[2020/11/16 11:11:26] root INFO: epoch: [0/100], iter: 10, lr: 0.001000, acc: 0.507812, loss: 0.698222, reader_cost: 6.01444 s, batch_cost: 6.29982 s, samples: 5632, ips: 89.39943
[2020/11/16 11:11:32] root INFO: epoch: [0/100], iter: 20, lr: 0.001000, acc: 0.500977, loss: 0.696527, reader_cost: 2.33420 s, batch_cost: 2.57432 s, samples: 5120, ips: 198.88761
[2020/11/16 11:11:37] root INFO: epoch: [0/100], iter: 30, lr: 0.001000, acc: 0.500000, loss: 0.695349, reader_cost: 2.34351 s, batch_cost: 2.57905 s, samples: 5120, ips: 198.52250
[2020/11/16 11:11:42] root INFO: epoch: [0/100], iter: 40, lr: 0.001000, acc: 0.500977, loss: 0.693913, reader_cost: …
```
> 日志符合benckmark规范

- ppocr/data/simple_dataset.py
att.
Sum of ratio list is not necessary to be 1.
> refine dynamic sampling

- MANIFEST.in
- doc/doc_ch/whl.md
- doc/doc_en/whl_en.md
- paddleocr.py
- setup.py
- tools/infer/predict_system.py
The update is as follows
1. paddleocr supports input of network pictures or numpy arrays
2. paddleocr whl support dygraph
3. drop_score will affect the output, not the drawing
4. Support the use of grayscale image as input, which will be converted to BGR in paddleocr
> paddleocr whl adaptation dygraph

- ppocr/data/__init__.py
评估DB时发现在2.0rc0 上会报错，报错大概是无法获得更多的共享内存，但是我的容器里/dev/shm/有空余的64G；eval设置为False可以解决这个问题
> set use_shared_momery as False when eval

- PPOCRLabel/libs/autoDialog.py
通过信号反复发送大量数据可能影响程序运行效率，最好不要发送识别结果到界面滚动显示
> 修改PPOCRLabel，避免程序运行速度越来越慢

- ppocr/optimizer/learning_rate.py
- ppocr/optimizer/lr_scheduler.py
- tools/program.py
1. Add CyclicalCosineDecay. The strategy can be seen in : https://arxiv.org/pdf/2012.12645.pdf. In ocr, without any fine tune on hyper-parameters, it can directly takes a 0.3% accuracy gain for CRNN(with 10% more training epochs).
2. modify the epoch num, because if we want to save models per 5epochs and total epoch is set as 50, then the 50th epoch  model will not be saved for the code before(the last epoch is actually 49).
> add CyclicalCosineDecay

- deploy/cpp_infer/include/preprocess_op.h
- deploy/cpp_infer/src/main.cpp
- deploy/cpp_infer/src/ocr_cls.cpp
- deploy/cpp_infer/src/ocr_det.cpp
- deploy/cpp_infer/src/ocr_rec.cpp
- deploy/cpp_infer/src/preprocess_op.cpp
开启TRT时图像需要resize到固定长度，会影响预测效果
原图：
不开启TRT预测结果：
开启TRT预测结果：
> Support fixed length TRT prediction

- configs/det/det_mv3_db.yml
- configs/rec/rec_icdar15_train.yml
- ppocr/data/__init__.py
> add use_shared_memory params for AIstudio demo

- tools/export_model.py
动机：由于PaddleOCR模型导出成ONNX之后，在ONNXRunTime运行时会check输入的shape，当模型的输入shape固定时，没办法推理不等于该shape的数据，但实际上模型支持dynamic shape。
修改：在导出det和cls模型时，将输入shape修改为[3,-1,-1]，在导出rec模型时，将输入shape修改为[3,32,-1]。
测试：自测predict_system.py预测结果，可正常预测。
> export_model support dynamic input shape

- PPOCRLabel/PPOCRLabel.py
Fixes syntax warnings in Python 3.9
```
find . -iname '*.py' | xargs -P4 -I{} python3.9 -Wall -m py_compile {}  
./PPOCRLabel/PPOCRLabel.py:1035: SyntaxWarning: "is" with a literal. Did you mean "=="?
if trans_dic["label"] is "" and mode == 'Auto':
./PPOCRLabel/PPOCRLabel.py:1794: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if result[0][0] is not '':
./PPOCRLabel/PPOCRLabel.py:1825: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if result[0][0] is not '':
./PPOCRLabel/PPOCRLabel.py:2011: SyntaxWarning: "is" with a literal. Did you mean "=="?
assert output is 0, "operate the cmd have some problems ,please check  whether there is a in the lib " \
```
> Fix syntax warning over comparison of literals using is.

- ppocr/data/imaug/make_shrink_map.py
fix the issue of  #1967 
refer to https://www.cnblogs.com/zzcpy/p/10524348.html
```
case1:
polygon = np.array([[1, 3], [5, 3], [5, 1], [1, 1]]).astype("float32")
area before the pr: 0.0
area before the pr: 8.0
case2:
polygon = np.array([[0, 0], [-1, 1], [0, 2], [1, 1]]).astype("float32")
area before the pr: 0.0
area before the pr: 2.0
```
> fix are calc for polygon

- StyleText/engine/predictors.py
- StyleText/engine/synthesisers.py
- StyleText/engine/text_drawers.py
att, improve style text infer process when the text is too long.
for the corpus: `Paddle12345678901234littletomatodonkey`
1. methods before: repeat bg according to the text input.(Cut off may also happen when is text is too long and the effect is not good for this case)
2. split text according to the style input, generate and then combine the results.
> improve style text infer process

- tools/program.py
- tools/train.py
ATT. Fix when
1. Info when dataloader length is 0.
2. print_batch_step is larger than the iters in an epoch.
> fix logger info for empty log

- ppocr/postprocess/rec_postprocess.py
修改srn模型postprocess，原后处理代码没有根据配置里的文件文本长度来预测
> fix srn_postprocess

- tools/infer/predict_system.py
When cv2.imwirte() saves ".gif", it will cause _error: (-2:Unspecified error) could not find a writer for the specified extension in function 'cv::imwrite_'. We add an _if_ statement to check whether the saving file format is ".gif" and covert the format to ".png" instead so as to avoid the error.
Now, it can work with ".gif" correctly.
Example:
> Fix the incompatibility of gif saving

- deploy/cpp_infer/include/postprocess_op.h
- deploy/cpp_infer/src/postprocess_op.cpp
求rectangle区域的平均分数，容易造成弯曲文本漏检。 求polygon区域的平均分数会更准确，但速度有所降低。 可按需选择
> add PolygonScoreAcc to improve polygon detect

- deploy/pdserving/README.md
- deploy/pdserving/README_CN.md
- deploy/pdserving/web_service.py
- deploy/pdserving/win/ocr_reader.py
- deploy/pdserving/win/ocr_web_client.py
- deploy/pdserving/win/ocr_web_server.py
New Feature
- 增加Win版本的Serving Web Service
- 增加README当中对Win运行Web Service的描述
- 把0.5.0 换成0.6.0并更改对应版本的用法
> pdserving support win and v0.6.0

- deploy/lite/Makefile
cherry-picked from #2895 
- Paddle-Lite C++ demo can not compile successfully
> [Paddle-Lite DEMO] Fix the issue that Paddle-Lite C++ demo can not compile successfully #2895

- deploy/cpp_infer/src/ocr_det.cpp
- deploy/cpp_infer/src/ocr_rec.cpp
- deploy/cpp_infer/src/preprocess_op.cpp
- deploy/cpp_infer/tools/build.sh
- tools/infer/utility.py
当前PR支持TRT变长预测，需要：
TensorRT 版本 >= 6.1.0.5
> suport TensorRT inference

- ppocr/losses/cls_loss.py
att
部分windows环境中，int为int32，会导致celoss计算类型错误
linux中，int为int64，这里强制做了类型转换
> fix cls type

- tools/infer/predict_e2e.py
调用训练模型时（infer_e2e.py）比调用inference模型时多一个预处理类：DecodeImage，在这里通过调用cv将字节数据转成图像数据以后又进行了红蓝通道交换，但是在调用inference模型时（predict_e2e.py）是直接通过cv读取的文件，并没有交换红蓝通道，导致最终的识别结果不一致。
> 修复 端到端算法调用inference模型时与训练模型结果不一致的问题，由rgb3个通道的顺序不一致引起

- deploy/paddle2onnx/readme.md
- tools/infer/predict_det.py
- tools/infer/predict_rec.py
1. 更新paddle2onnx 部署文档，支持OCR动态shape的转换
2. 修复当采用固定shape转换onnx时，输入数据应该和onnx的输入大小保持一致
3. 解决issue: https://github.com/PaddlePaddle/Paddle2ONNX/issues/451
4. 解决issue: https://github.com/PaddlePaddle/PaddleOCR/issues/5055
> update paddle2onnx readme and fix a bug for onnx（issue:5055)

- deploy/android_demo/app/src/main/java/com/baidu/paddle/lite/demo/ocr/Predictor.java
In the Predictor class of the Android sample code, the default value of the inputStd variable is wrong, because the default value read from strings.xml is 0.485, 0.456, 0.406. Since the variable has been reassigned, this bug is not easy to find.
> fix the default value of predictor inputStd in android example

- doc/doc_ch/customize.md
PaddleOCR中几乎所有的Markdown文档都不规范（没有符合markdownlint标准），如下图所示。
规范的代码对于一个项目的重要性是不言而喻的，同样Markdown文档也需要符合规范。
我坚决不允许这么优秀的开源项目的文档写得不规范！！！
我这次只把`doc/doc_ch/customize.md`文档规范了，如果贵项目也觉得有必要规范一下文档，那么我们可以一起进行文档的规范化工作。
> 使用markdownlint规范Markdown文档

- ppocr/optimizer/learning_rate.py
- ppocr/optimizer/lr_scheduler.py
论文链接](https://arxiv.org/pdf/2012.12645.pdf)     
[参考代码](https://pytorch.org/docs/stable/_modules/torch/optim/lr_scheduler.html#OneCycleLR)     
**我的工作**   
- 将pytorch代码转换成paddle代码，按照PaddleOCR的代码风格集成到项目中。
- 调整代码，没有使用源码中有关momentum的参数。
- 在自己的中文数据集(200W+)上做实验验证结构的可行性：
- 不加载预训练模型进行训练(30轮)，backbone模型用的是MobileNetV1Enhance，学习率策略为：name: Piecewise decay_epochs : [20, 30]. values : [0.01, 0.002]. warmup_epoch: 1. 训练acc75%，验证集acc86%。
- 不加载预训练模型进行训练(30轮)，backbone模型用的是MobileNetV1Enhance，学习率策略为：name: OneCycle max_lr: 0.01。训练acc79%，验证集87%。
- 实验环境及参数    
单机4卡(V100，32G)，num_workers=8，batch_size=256
[onecycle.zip](https://github.com/PaddlePaddle/PaddleOCR/files/7860663/onecycle.zip)
注：由于https://github.com/PaddlePaddle/PaddleOCR/pull/5171 cla认证问题，重新提交新的pr。
> add onecycle

- ppocr/modeling/backbones/__init__.py
- ppocr/modeling/backbones/rec_micronet.py
[论文链接](https://arxiv.org/abs/2108.05894)   
[参考代码](https://github.com/liyunsheng13/micronet)    
**我的工作**
- 将pytorch代码转换成paddle代码，按照PaddleOCR的代码风格集成到项目中。    
- 调整代码，使backbone结构输出的维度为[n, 432, 1, 80]
- 在自己的中文数据集(200W+)上做实验验证结构的可行性：
- backbone网络结构为MicronetM0时，训练时的IPS值在90左右，训练了30轮，训练时acc为57%左右，验证集准确率为77%。
- backbone网络结构为MicronetM3时，训练时的IPS值在50左右，非常慢。所以没有进行30轮的训练。
- **经过分析：模型耗时的地方在作者提出的Dynamic Shift-Max激活函数，我将此激活函数替换成Rule6激活函数，** backbone网络结构为MicronetM3时，训练时的IPS值在150左右，训练了30轮，训练时acc为67%左右，验证准确率为82%。
- 实验环境及参数    
单机4卡(V100，32G)，num_workers=8，batch_size=256
[micronet.zip](https://github.com/PaddlePaddle/PaddleOCR/files/7860559/micronet.zip)
注：由于https://github.com/PaddlePaddle/PaddleOCR/pull/5169 cla认证问题，重新提交新的pr。
> add micronet

- ppocr/losses/rec_ctc_loss.py
- tools/program.py
ips与log打印的日志无法对应（按照ips计算得出的训练耗时与实际log的时间戳不同）
* 修复ips信息可视化结果
* 添加训练时计算metric的时间间隔控制，加速训练
* 将ctc loss的pred_length生成在cpu上（本身ctc loss计算，也要求数据在cpu上），防止cloud上v100训练hang住的问题，同时减少个gpu->cpu拷贝
* 命令：`python tools/train.py -c configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec.yml`
* 可视化结果：
* 命令：`python tools/train.py -c configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec.yml`
* 可视化结果：
* 命令：`python tools/train.py -c configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec.yml -o Global.calc_epoch_interval=10`
* 可视化结果（ips 255 -> ~330）：
* 命令：`python tools/train.py -c configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec.yml -o Global.calc_epoch_interval=10`
* 可视化结果(eta 7d18h -> 7d6h)：
> fix ips info and reduce interval of metric calc

- doc/doc_en/training_en.md
This is a cherry-pick which was committed to the release/2.4 branch (PR #5320) but not included in the dygraph branch.
> Fix the broken link in doc/doc_en/training_en.md

- configs/rec/rec_efficientb3_fpn_pren.yml
- ppocr/data/imaug/__init__.py
- ppocr/data/imaug/label_ops.py
- ppocr/data/imaug/rec_img_aug.py
- ppocr/losses/__init__.py
- ppocr/losses/rec_pren_loss.py
- ppocr/modeling/backbones/__init__.py
- ppocr/modeling/backbones/rec_efficientb3_pren.py
- ppocr/modeling/heads/__init__.py
- ppocr/modeling/heads/rec_pren_head.py
- ppocr/modeling/necks/__init__.py
- ppocr/modeling/necks/pren_fpn.py
- ppocr/postprocess/__init__.py
- ppocr/postprocess/rec_postprocess.py
- tools/eval.py
- tools/export_model.py
- tools/program.py
论文地址：[arxiv](https://arxiv.org/abs/2105.04286)
原作者代码地址：[@RuijieJ](https://github.com/RuijieJ/pren) 非常感谢大佬的源码！才让我这个菜B比较顺利的完成复现。
本次提交相比于前面的论文复现赛所提交的代码干净又卫生🤣
> 注：有diff的原因大都是基于保持仓库代码的整洁、干净以及相似函数、类逻辑一致的出发点进行的合理改动。如果有需要，我也可以再改回来...
>
> 如果想查阅和原论文实现完全一致的代码实现，可以参考：[基于PPOCR的PREN复现repo](https://github.com/OneYearIsEnough/PaddleOCR/tree/pren_juanbudong)
1. 取消训练时label对长度的限制：[链接](https://github.com/OneYearIsEnough/PaddleOCR/blob/4a8d20187d3fb6a5af687a8dd14996990d986ad9/ppocr/data/imaug/label_ops.py#L835)
2. 取消训练、评估时对label强制转小写的限制：[链接](https://github.com/OneYearIsEnough/PaddleOCR/blob/4a8d20187d3fb6a5af687a8dd14996990d986ad9/ppocr/data/imaug/label_ops.py#L818)
3. 取消训练、评估时对宽或高不超过5的图片的过滤策略：[链接](https://github.com/OneYearIsEnough/PaddleOCR/blob/4a8d20187d3fb6a5af687a8dd14996990d986ad9/ppocr/data/imaug/rec_i …
> [Feature] Add PREN Scene Text Recognition Model(Accepted in CVPR2021)

- tools/infer/predict_cls.py
- tools/infer/predict_det.py
- tools/infer/predict_e2e.py
- tools/infer/predict_rec.py
- tools/infer/predict_system.py
- tools/infer_cls.py
- tools/infer_det.py
- tools/infer_e2e.py
- tools/infer_kie.py
- tools/infer_rec.py
- tools/infer_table.py
- tools/infer_vqa_token_ser.py
- tools/infer_vqa_token_ser_re.py
- tools/train.py
环境变量中包含多个tools目录的时候，需要保证当前运行的tools目录在path的最前面，从而使得函数等内容可以被成功引用
> fix import order

- deploy/cpp_infer/src/ocr_rec.cpp
修改cpp端 batch_width计算逻辑以解决batch_width和实际的图片w不一致的问题
修改前
修改后，
> [Cpp Infer] fix bug in mem copy

- benchmark/run_benchmark_det.sh
避免benchmark 模型log叠加，多卡执行前删掉 ./mylog
> fix run_benchmark_det.sh

- test_tipc/test_inference_cpp.sh
解决编译opencv之后，编译ocr inference demo路径错误的问题。
https://github.com/PaddlePaddle/PaddleOCR/blob/c70f769eca3c0a179e745bc8356af942438e0442/test_tipc/test_inference_cpp.sh#L169
> [TIPC] Fix cmake path bug

- ppocr/utils/logging.py
- test_tipc/supplementary/config.py
- tools/infer_vqa_token_ser_re.py
- tools/program.py
某些情况下，当其他程序配置了root logger后，会造成当前logger重复打印两次，这是因为所有logger都是继承自root logger，因此会打印两次。将logger.propagate设置False可避免这种情况 ，设置之后不能使用root logger，需要使用自定义的logger
> fix log print twice error

- deploy/hubserving/ocr_cls/__init__.py
- deploy/hubserving/ocr_cls/module.py
- deploy/hubserving/ocr_cls/params.py
- deploy/hubserving/ocr_det/__init__.py
- deploy/hubserving/ocr_det/module.py
- deploy/hubserving/ocr_det/params.py
- deploy/hubserving/ocr_rec/__init__.py
- deploy/hubserving/ocr_rec/module.py
- deploy/hubserving/ocr_rec/params.py
- deploy/hubserving/ocr_system/__init__.py
- deploy/hubserving/ocr_system/module.py
- deploy/hubserving/ocr_system/params.py
- deploy/hubserving/readme.md
- deploy/hubserving/readme_en.md
- deploy/hubserving/structure_system/__init__.py
- deploy/hubserving/structure_system/config.json
- deploy/hubserving/structure_system/module.py
- deploy/hubserving/structure_system/params.py
- deploy/hubserving/structure_table/__init__.py
- deploy/hubserving/structure_table/config.json
- deploy/hubserving/structure_table/module.py
- deploy/hubserving/structure_table/params.py
- paddleocr.py
- ppstructure/predict_system.py
- ppstructure/utility.py
- tools/test_hubserving.py
包含一个删除和两个新增和两处bug修复
删除
1. 从PP-Structure中删除VQA的推理
新增
1. hubserving新增structure_system用于PP-Structure的推理
3. hubserving新增structure_table用于表格识别的推理
修复
1. 修复`ocr_det`,`ocr_cls`,`ocr_rec`和`ocr_system`中的`module.py`文件单独执行时的未初始化问题
2. 修复 paddlehub的import问题
> add PP-Structure to hubserving

- deploy/cpp_infer/include/paddleocr.h
- deploy/cpp_infer/include/utility.h
- deploy/cpp_infer/src/main.cpp
- deploy/cpp_infer/src/paddleocr.cpp
- deploy/cpp_infer/src/utility.cpp
1. fix mkdir error in win
2. Rename PaddleOCR to PPOCR to avoid name conflict with namespace
> rename PaddleOCR to PPOCR

- tools/infer/predict_system.py
在使用tools/infer/predict_system.py对韩文进行预测时，无法保存韩文到用于存放识别结果的system_results.txt文件，并报错：
修改之后能够正常保存：
> bugfix: unable to save Korean to the specified file: system_results.txt

- PPOCRLabel/PPOCRLabel.py
打开图片，不使用自动标注，图片没有任何的标注框。
kie标注了一个框之后，右键框点击重新识别，拿到了文字结果，然后复制几个框之后，点击软件右上角的重新识别后会报错。
> [PPOCRLable BUG] Fix kie Re-recognition crash 🐛 

- ppocr/data/imaug/copy_paste.py
If you train data with CopyPaste and EastRandomCropData such as [ch_PP-OCRv3_det_cml.yml](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_cml.yml).
The original copy_paste only appends the new polys and new ignore_tags to data, but no new texts value to data.  In EastRandomCropData, the texts value is an important key in below https://github.com/PaddlePaddle/PaddleOCR/blob/473a811667adcc2706c8cfa6d04a66f9fbce02d7/ppocr/data/imaug/random_crop_data.py#L170-L179
If you tranform the train data with no new texts, you will get a wrong label. So append the texts to CopyPaste.
> Fix copy_paste no texts augment.

- tools/infer/utility.py
DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
> fix DeprecationWarning,

- deploy/android_demo/app/src/main/cpp/native.cpp
fix issue 6640
cpu_mode can not change by argument
在 src/main/cpp/native.cpp
的函数` static paddle::lite_api::PowerMode str_to_cpu_mode(const std::string &cpu_mode) `中
第50行
`auto index = cpu_mode_map.find(upper_key);`
无论输入什么 cpu_mode 都会报错 cpu_mode not found
改为
`auto index = cpu_mode_map.find(upper_key.c_str());`
则正常
> Update native.cpp fix issue 6640

- tools/infer/predict_system.py
使用`tools/infer/predict_system.py`进行推理，使用多进程时预测结果只会保存一份，这是因为命名结果一致导致的覆盖：
```python
with open(os.path.join(draw_img_save_dir, "system_results.txt"), 'w', encoding='utf-8') as f:
f.writelines(save_results)
```
将原有的文件路径修改为了带进程id的路径，从而可以保存完整结果。
```python
if args.total_process_num > 1:
save_results_path = os.path.join(draw_img_save_dir, f"system_results_{args.process_id}.txt")
else:
save_results_path = os.path.join(draw_img_save_dir, "system_results.txt")
with open(save_results_path, 'w', encoding='utf-8') as f:
f.writelines(save_results)
```
> fix multiprocess overwrite

- deploy/lite/crnn_process.cc
- deploy/lite/ocr_db_crnn.cc
1. crnn_process.cc文件的CrnnResizeImg方法没有定义resize_img变量，并且没有返回值；
2. ocr_db_crnn.cc文件中调用RunRecModel方法时缺少参数
> fix compile bug

- ppocr/metrics/rec_metric.py
- ppstructure/table/table_metric/table_metric.py
- ppstructure/vqa/tools/eval_with_label_end2end.py
- requirements.txt
This PR replaces GPL licensed libraries for string comparisions with rapidfuzz which has the following advantages:
- MIT license compatible with the Apache License of PaddleOCR, which is not the case for the currently used GPL licensed libraries
- interface provides a normalized distance, which makes it possible to simplify the code here
- faster implementation than both python-Levenshtein and distance
- actively maintained, which is not the case both for python-Levenshtein and distance
- provides wheels for all common platforms, which simplifies the installation for users
> replace GPL licensed components

- test_tipc/benchmark_train.sh
Default epoch: 8
The benchmark epoch is `8*1*1`  for N1C1.
The benchmark epoch is `8*1*4`  for N1C4.
The benchmark epoch is `8*4*8`  for N4C8.
> [tipc] set benchmark_train dynamic epoch

- ppocr/data/imaug/rec_img_aug.py
limit max_wh_ratio as the ratio can be higher than max_wh_ratio.
```
resize_shape = (3,32, 320)
wrong = np.zeros((32, 325, 3))
y= resize_norm_img_chinese(wrong, resize_shape)[0]
y.shape = (3, 32, 325)
```
reference: #7108 @andyjpaddle
> limit maximum resizing ratio

- PPOCRLabel/PPOCRLabel.py
- configs/table/SLANet_ch.yml
解决了导出 JSON 文件时，L2534 将 "cells" 写成 "cell" 的问题。因如下代码取的是cells，否则在训练载入数据时会报 keyerror 的错误。
https://github.com/PaddlePaddle/PaddleOCR/blob/282eebbd660886c38d4ae91bcbcd70b5cdc03f75/ppocr/data/pubtab_dataset.py#L102
> 更新 PPOCRLabel 导出 JSON 文件的错误，更新了配置文件 SLANet_ch.yml 中 Eval - datadir 前多余的空格。

- tools/infer/predict_system.py
- tools/infer/utility.py
增加draw_ocr_box_txt2:
1. 文本框倾斜时，draw_ocr_box_txt将文字画在文本框外边，看起来非常不舒服，解决了此问题；
2. 只传入文本框位置 而没有文本内容时也能显示。
3. 自动调整字体大小 ，避免超出文本框而被截断。
博客地址：https://blog.csdn.net/sdlypyzq/article/details/126654452
> 增加draw_ocr_box_txt2:解决文本框倾斜时文字画在外边的情况

- test_tipc/test_train_inference_python_npu.sh
- test_tipc/test_train_inference_python_xpu.sh
- tools/infer/utility.py
- tools/program.py
为昇腾和昆仑设备添加 TIPC 脚本
```bash
bash test_tipc/prepare.sh \
test_tipc/configs/ch_PP-OCRv2_det/train_infer_python.txt 'lite_train_lite_infer'
bash test_tipc/test_train_inference_python.sh \
test_tipc/configs/ch_PP-OCRv2_det/train_infer_python.txt 'lite_train_lite_infer'
bash test_tipc/test_train_inference_python_npu.sh \
test_tipc/configs/ch_PP-OCRv2_det/train_infer_python.txt 'lite_train_lite_infer'
bash test_tipc/test_train_inference_python_xpu.sh \
test_tipc/configs/ch_PP-OCRv2_det/train_infer_python.txt 'lite_train_lite_infer'
```
昆仑运行结果如下：
> [TIPC] add scripts for NPU and XPU, test=develop

- PPOCRLabel/PPOCRLabel.py
https://github.com/PaddlePaddle/PaddleOCR/issues/7753 
autoSaveFunc(self)修改后没有对shape进行保存
> [bug fix] KIE模式下关键字无法保存

- PPOCRLabel/libs/canvas.py
https://github.com/PaddlePaddle/PaddleOCR/issues/7681  
https://github.com/PaddlePaddle/PaddleOCR/issues/7702  
self.prevPoint存储使用浮点型，p.drawLine只接受整型，触发上述异常。
> canvas.paintEvent() bug fix

- configs/kie/kie_unet_sdmgr.yml
- ppocr/metrics/kie_metric.py
There's a hard-coded ignores list for computing the F1 score while evaluating the model. If the class list of data is modified, the ignore list should be modified as well, otherwise, the F1 score could not reflect the actual performance of the model.
Instead of changing the hidden and hard-coded ignore class list, this change makes it configurable via the model config YAML file.
> [KIE] add configurable ignore classes for KIEMetric

- doc/doc_ch/inference_ppocr.md
- doc/doc_en/inference_ppocr_en.md
> add trt infer doc

- deploy/cpp_infer/src/preprocess_op.cpp
- deploy/cpp_infer/src/utility.cpp
1. 将rec模型预处理中的padding值，由127换为0.
2. 检测Box的排序，曾经漏掉了第一个box和第零个box的check.
> Fix padding value in rec model and box sort in det model

- configs/table/table_mv3.yml
修复table模型再amp o1和o2下的低精度问题
原因：输入数据数值超过fp16表示范围导致误差较大
> Add matmul_v2 and elementwise_add to black list for amp o1 and o2

- tools/train.py
修复rec v3模型amp训练精度偏低问题：由于该模型中matmul调用BatchedGEMM，框架默认使用FP16累加因此会损失精度。
本PR通过环境变量FLAGS_gemm_use_half_precision_compute_type=False，使BatchedGEMM使用FP32累加，AMP-O1和O2可达到精度对齐。
> matmul use fp32 compute_type

- doc/doc_en/quickstart_en.md
The link provided for installing paddlepaddle doesn't work. Hence, this change updates the broken link to install paddlepaddle for CPU and GPU.
> Fix broken link to install paddlepaddle

- ppstructure/docs/quickstart_en.md
This proposed change fixes the broken link under the section `2.4 Parameter Description` in the last line that says: Most of the parameters are consistent with the PaddleOCR whl package, see `whl package documentation`.
> Fix: broken link for whl package documentation.

- doc/doc_en/whl_en.md
The English version uses img_path for ocr, even though img is loaded by imread.
> Fix the mismatch of document between Chinese and English

- tools/infer/predict_system.py
The index j will skip 0. That will not swap the first with second, even if the first  box is actually on the second right.
```
for i in range(num_boxes - 1):
for j in range(i, 0, -1):
```
> Fix sorted_boxes() function bug: the index j can not skip 0.

- tools/infer/utility.py
在python代码中使用：
`os.environ['CUDA_VISIBLE_DEVICES'] = '1'`
无法指定使用第2块显卡，始终会使用第一张显卡；
通过查看源码，发现tools/infer/utility.py中存在如下代码：
`config.enable_use_gpu(args.gpu_mem, 0)`
设置是使用第一个gpu，即id是0的GPU，通过将上述代码修改为第2块显卡的id，可以将推理放在第2块显卡：
`config.enable_use_gpu(args.gpu_mem, 1)`
但这样做侵入太大且不够灵活，因此在推理模块的初始化参数中，新增了`args.gpu_id`参数，这样就可以在推理时使用特定GPU进行推理！
> 新增gpu_id参数，可以在推理时使用特定GPU进行推理

- ppocr/postprocess/east_postprocess.py
EAST模型的后处理代码中导入了lanms模块却没有使用，导致后处理缓慢，严重影响了训练中的评估速度。
> Fix low speed bug of eval during training for EAST

- test_tipc/configs/layoutxlm_ser/ser_layoutxlm_xfund_zh.yml
- N1C1 num_worker = 16 can gain better performance
- N1C8 may still need debugging for better performance
> change num worker to 16 for better performance

- configs/kie/layoutlm_series/ser_layoutlm_xfund_zh.yml
- test_tipc/configs/layoutxlm_ser/ser_layoutxlm_xfund_zh.yml
- N1C1 num_worker = 16 can gain better performance
- N1C8 may still need debugging for better performance
- The former PR https://github.com/PaddlePaddle/PaddleOCR/pull/9173 only adjust the tipc config
> change num worker to 16 for better

- ppocr/data/imaug/label_ops.py
Change `np.bool` to `bool` since `np.bool` was originally deprecated in NumPy 1.20.
> Fix numpy.bool deprecation problem

- configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml
- configs/table/SLANet.yml
- test_tipc/configs/slanet/SLANet.yml
- tools/program.py
- tools/train.py
O2下因改为promote策略，会有一些算子原来使用fp16计算，在策略更新后选择了fp32计算，导致性能下降。
通过加入自定义白名单，模型算子运行的数量和类型和AMP升级前可达到一致，同时恢复到原始性能
> 修复动态图O2模型修改为promote策略后引起的性能下降问题

- paddleocr.py
This update is to fix PaddleOCR package import compatibility issue. 
For instance, at moment, user cannot import both paddleocr & detectron2 at same time due to conflicting importing issues.
With this enhancement, paddleocr can be successfully imported  along side with detectron2.
> Improve package import compatibility

- configs/det/ch_PP-OCRv2/ch_PP-OCRv2_det_cml.yml
- tools/program.py
- tools/train.py
背景：ch_PP-OCRv2_det 模型在amp fp16训练中，O1、O2都会出现nan，原因是模型中卷积层的数值范围极大，超出了fp16的表示范围，并不适合这种训练方式。我们尝试了amp bf16 训练，发现无需任何额外配置，模型未出现nan，精度和相同配置下的fp32训练可以对齐。
PR：为套件添加amp_dtype的选项，默认为float16，给ch_PP-OCRv2_det 模型配置为bfloat16
> improve amp training

- deploy/slim/prune/export_prune_model.py
- deploy/slim/prune/sensitivity_anal.py
- deploy/slim/quantization/export_model.py
- deploy/slim/quantization/quant.py
- deploy/slim/quantization/quant_kl.py
- ppocr/data/__init__.py
- ppocr/utils/save_load.py
- tools/eval.py
- tools/export_center.py
- tools/infer_det.py
- tools/program.py
- tools/train.py
修改代码以提升PaddleCV套件一致性，同时适配X项目。修改后，套件应满足如下一致性要求：
1. 将训练过程中最优（一般是验证集上精度最高）的模型权重存储在输出目录的`best_model`子目录中，文件命名为`model.pdparams`。与之相配套的优化器参数（如果存储的话）文件命名为`model.pdopt`，也存储在该目录中。
2. 支持将训练、验证过程中VisualDL产生的.log格式日志文件保存在输出目录中（无嵌套子目录）。
3. 套件根目录存在`requirements.txt`文件，指定使用套件基础功能需要的依赖。在套件根目录可通过`pip install .`或`pip install -e .`方式（至少其中一种）安装套件核心库。
4. 对于模型导出功能，默认支持或通过命令行选项/配置文件等手段支持导出为FD格式。『FD格式』的导出结果通常包含如下文件：
- `inference.pdiparams`：保存权重参数。
- `inference.pdiparams.info`：保存与参数有关的额外信息。
- `inference.pdmodel`：保存模型结构描述信息。
- （可选）`inference.yml`：预处理配置文件。
1. 【一致性提升】使训练时检查点存储位置满足一致性要求1。
2. 【一致性提升】【**不兼容升级**】修改VisualDL日志存储位置以满足一致性要求2。
3. 【功能增强】修改`tools/infer_det.py`中`raw_det_res`对『零目标框』情形的处理逻辑，在该情形下仍然存储图像（存的是原图），从而使用户在各种情况下均能获得输出图像，而无需关注目标框数量。
4. 【功能增强】调整signal handlers的设置时机。修改前，signal …
> Toward Devkit Consistency

- configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_cml.yml
背景：ch_PP-OCRv3_det 模型在amp fp16训练中，O1、O2都会出现nan，原因是模型中卷积层的数值范围极大，超出了fp16的表示范围，并不适合这种训练方式。我们尝试了amp bf16 训练，发现无需任何额外配置，模型未出现nan，精度和相同配置下的fp32训练可以对齐。
PR：为套件添加amp_dtype的选项，默认为float16，给ch_PP-OCRv3_det 模型配置为bfloat16
> improve amp training 

- doc/doc_ch/kie.md
ser_vi_layoutxlm_xfund_zh.yml中的Architecture.Backbone.num_classes所赋值会设置给Loss.num_classes， 由于采用BIO标注，假设字典中包含n个字段（包含other）时，则类别数为2n-1;假设字典中包含n个字段（不含other）时，则类别数为2n+1。
> 补充num_classes注释说明

- test_tipc/test_train_inference_python_npu.sh
1. 将npu tipc中耗时较长的模型的epoch修改为1
2. npu目前不支持sync_bn，修改模型配置中的use_sync_bn=false
> [npu-tipc] update npu tipc scripts

- deploy/hubserving/readme.md
- deploy/hubserving/readme_en.md
- deploy/pdserving/README_CN.md
- doc/doc_ch/models_list.md
- doc/doc_en/models_list_en.md
- setup.py
- 指出可能需要删除`__pycache__`后对`params.py`的更改才能通过`hub install`生效（不然只会安装`__pycache__`中的修改前版本）
- 提示如何重命名模块
- 以及其他大量markdown格式改进
- 指出所有英文识别模型的字典文件均为`ppocr/utils/en_dict.txt`而不是中文模型中的`ppocr/utils/ppocr_keys_v1.txt`
> 改进文档`deploy/hubserving/readme.md`和`doc/doc_ch/models_list.md`

- deploy/docker/hubserving/README_cn.md
现有的Markdown文档中引用地址多了一个括号导致无法正常打开页面。
> 修复测试服务中图片转Base64的引用地址错误。

- requirements.txt
由于新版Pillow库去除了`FreeTypeFont.getsize`接口（[PaddleOCR中该API使用情况](https://github.com/search?q=repo%3APaddlePaddle%2FPaddleOCR%20getsize&type=code)），PaddleOCR无法在Pillow>9.5.0以上版本工作。因此，在依赖列表中限制Pillow版本。参见：
https://github.com/XingangPan/DragGAN/issues/152
> Limit Pillow Version

- StyleText/engine/text_drawers.py
- applications/PCB字符识别/gen_data/gen.py
- ppocr/data/imaug/rec_img_aug.py
- ppocr/utils/visual.py
- ppstructure/utility.py
- requirements.txt
- tools/infer/predict_rec.py
- tools/infer/utility.py
- 修改requirements.txt，pillow版本10.0.0以上
- 修改相关联的文件，修改长宽获取api
- 修改常量名称： Image.ANTIALIAS-> Image.LANCZOS
ex:
- previous:
```
width, height = font.getsize("Hello world")
```
- Now:
```
left, top, right, bottom = font.getbbox("Hello world")
width, height = right - left, bottom - top
```
> upgrade pillow to 10.0.0

- paddleocr.py
- tools/infer/predict_system.py
When processing multiple images PaddleOCR currently breaks if even a single image is malformed. This is to prevent that.
> Don't break overall processing on a bad image

- tools/infer/utility.py
> [MLU] add mlu device for infer

- test_tipc/prepare.sh
修复table_master模型在跑TIPC的lite_train_lite_infer模式时报错找不到数据的问题
> fix bug for table_master in tipc when running 'lite_train_lite_infer' mode

- ppocr/modeling/heads/rec_robustscanner_head.py
Paddle支持stride后，需要检查动转静不一致的情况。但检查难度大，简单的检查会有误报，但这种方式获得评审会的同意。通过with可以避免误报。
> paddle support stride, fix dy2st check

- ppocr/data/imaug/ct_process.py
- ppocr/utils/utility.py
by current PR, remove un-used imported modules in code, so to avoid PyInstaller packaged binary 's py-script import them, which in fact is not included by pyinstaller when package. 
if not merge current PR , then PyInstaller should add parameter `--hidden-import imghdr --hidden-import scipy.io` and must add parameter `--collect-all  paddleocr` , but the previous parameter is not suggested to hidden-import un-used modules for package release. 
Previously there is a [commit](https://github.com/PaddlePaddle/PaddleOCR/commit/32fe3c9b07f125b0c2e47d6a47776d128ee6847b) has `Improve package import compatibility` of paddleocr.py file. but the pyinstaller packaged execution file runtime not found module issue still exists.
I had tried another PR https://github.com/PaddlePaddle/PaddleOCR/pull/10421 …
> remove un-used imported modules, so to avoid PyInstaller packaged binary runtime error

- ppocr/postprocess/rec_postprocess.py
- ppstructure/predict_system.py
- ppstructure/utility.py
- tools/infer/predict_rec.py
- tools/infer/predict_system.py
- tools/infer/utility.py
* modification of return word box
* update_implements
* Update rec_postprocess.py
* Update utility.py
> [Cherry-pick] #10515

- .pre-commit-config.yaml
- ppocr/data/simple_dataset.py
由于在修改了dbnet数据增强的个数及顺序后，会导致ocrv4新增加的dsr增强失效，因此将其从固定索引改为检索索引，可以避免增加或减少数据增强后的错误
> 修改数据增强导致的DSR报错

- doc/doc_en/algorithm_overview_en.md
> fix typo in algorithm_overview_en.md

- paddleocr.py
https://github.com/PaddlePaddle/PaddleOCR/issues/10533
> 实现功能：当--savefile为true时，在--output下以当前图片名称后接“.txt”为文件名保存ocr推理结果，解决了issues：

- tools/infer/predict_rec.py
I have the problem running OCR with CPU/GPU that I run through both AWS EC2 instance and my local machine (CPU) and see memory increase infinitely.
There are some issues like me such as:
- https://github.com/PaddlePaddle/PaddleOCR/issues/7823
- https://github.com/PaddlePaddle/PaddleOCR/issues/4452
- https://github.com/PaddlePaddle/PaddleOCR/issues/7155
After tracing, I see `predict_rec.py` not release memory when predicted. I add `self.predictor.try_shrink_memory()` like in `predict_cls.py` and it works.
> fix: release memory after predict

- tools/train.py
#10700
-1 index, not DistillationNRTRLoss。
A more elegant way to check if loss_config_list contains DistillationNRTRLoss.
> ch_PP-OCRv4_rec_distill.yml, fix KeyError: 'NRTRLabelDecode'

- deploy/cpp_infer/src/paddlestructure.cpp
PaddleStructure::rebuild_table函数中`structure_boxes`的索引用错了，可能导致dis和iou无法正确计算。
原代码段：
```
for (int j = 0; j < structure_boxes.size(); j++) {
if (structure_boxes[i].size() == 8) {
structure_box = Utility::xyxyxyxy2xyxy(structure_boxes[j]);
} else {
structure_box = structure_boxes[j];
}
dis_list[j][0] = this->dis(ocr_box, structure_box);
dis_list[j][1] = 1 - Utility::iou(ocr_box, structure_box);
dis_list[j][2] = j;
}
```
应改为：
```
for (int j = 0; j < structure_boxes.size(); j++) {
if (structure_boxes[j].size() == 8) {
structure_box = Utility::xyxyxyxy2xyxy(structure_boxes[j]);
} else {
structure_box = structure_boxes[j];
}
dis_list[j][0] = this->dis(ocr_box, structure_box);
dis_list[j][1] = 1 - Utility::iou(ocr_box, structure_box);
dis_list[j][2] = j;
}
```
> Fix index variable in for loop in paddlestructure.cpp

- configs/rec/rec_r45_abinet.yml
- tools/export_model.py
When exporting the inference model for ABINet, adapt to the 'image_shape' of ABINetRecResizeImg.
> rec_r45_abinet for export model

- ppocr/modeling/heads/table_master_head.py
在循环次数为 0 时，`cls_x` 和 `bbox_x` 是不存在的，因此是有风险的，也会导致动转静 PaddleSOT 报错
> fix `cls_x` and `bbox_x` is possibly unbound

- deploy/paddle2onnx/readme.md
- deploy/paddle2onnx/readme_ch.md
Fixed command line argument path
修正了转换步骤里的命令参数
> Update ONNX conversion readme_ch.md

- tools/infer/predict_rec.py
cherry-pick of https://github.com/PaddlePaddle/PaddleOCR/pull/10962
> Fixed bug with "max_text_length" for VisionLAN

- PPOCRLabel/gen_ocr_train_val_test.py
* Bug fixes
* Others
* Fix split function where it failed to correctly set paths on different platform
> Cherrypicking GH-10923 to PaddleOCR:dygraph

- ppocr/modeling/heads/rec_satrn_head.py
Bug fixes
Models
fix satrn export for paddle2.5
> fix satrn export for paddle2.5

- configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_cml.yml
Bug fixes
Others 
1. 修复了找不到模型的问题，原因是PPLCNetNew不在可选模型名称的列表内，将PPLCNetNew改为PPLCNetV3；
2. 修复了db_fpn.py解析in_channels的报错问题，db_fpn.py中按序列解析in_channels，而lcnetv3.py中det为false时输出是数值，为true才返回序列。在两个student模型的backbone中添加"det: true"；
3. 修复了训练过程中eval时的显存溢出问题。通过限制过大的测试数据可解决该问题，具体调整是，在eval→DetResizeForTest的配置中增加"limit_side_len: 960,limit_type: max"。
> v4 det cml configs

- PPOCRLabel/gen_ocr_train_val_test.py
使用gen_ocr_train_val_test.py分割recognition data後產生的train.txt、val.txt和test.txt每行label間多出一行空格行(\n)，導致訓練時出現異常，移除換行\n後便可正常運行。
因多出一行空格行，導致以下error。
`[2023/11/21 09:58:27] ppocr ERROR: When parsing line D:\PaddleOCR\train_data\rec\train\FAB06_input_Win 2000_crop_1.jpg l
, error happened with msg: Traceback (most recent call last):
File "D:\PaddleOCR\ppocr\data\simple_dataset.py", line 252, in __getitem__
data['ext_data'] = self.get_ext_data()
File "D:\PaddleOCR\ppocr\data\simple_dataset.py", line 124, in get_ext_data
label = substr[1]
IndexError: list index out of range`
> 解決recognition的train test分割程式執行後的文檔每行間多出一行空格

- paddleocr.py
This commit resolves the issue where `dt_boxes` was evaluated as a boolean in Python 3.11, leading to a ValueError. The condition `if not dt_boxes:` is replaced with `if dt_boxes.size == 0:` to explicitly check for an empty array, ensuring compatibility with Python 3.11 and maintaining the intended functionality.
Bug Fixes
Others
When using PaddleOCR in a Python 3.11 environment, an error is encountered during text detection only mode (`det=True, rec=False`). The error arises from the evaluation of `dt_boxes` as a boolean condition in an `if not dt_boxes:` statement. This behavior leads to a `ValueError` due to the ambiguous boolean evaluation of a NumPy array with more than one element. 
Python 3.11
```
ValueError: The truth value of an array with more than one element is ambiguous. Use …
```
> Fix for Ambiguous Boolean Evaluation Error in PaddleOCR with Python 3.11

- PPOCRLabel/PPOCRLabel.py
- PPOCRLabel/libs/canvas.py
- PPOCRLabel/libs/editinlist.py
- PPOCRLabel/resources/strings/strings-en.properties
- PPOCRLabel/resources/strings/strings-zh-CN.properties
- paddleocr.py
- ppstructure/utility.py
[ New features | Bug fixes ]
[ Models ]
1、PPOCRLabel现在支持从中文路径导入图片，原本导入含中文路径的图片会导致崩溃。
2、PPOCRLabel现在支持移动被其他框覆盖的锚点，原本无法移动被覆盖的锚点。
3、修复utility.py中误输入字符导致的语法错误。
4、修复setValue()应输入int，实际输入float导致的类型错误。
5、修复paddleocr中未import predict_system的错误。
6、修复canvas.py中部分输入参数类型错误
7、修复了LabelList不兼容搜狗输入法或win11输入法的问题。原本使用搜狗输入法修改标注数据时，仅输入一个字母就会失去焦点并提交数据变更，导致无法输入完整的汉字。现在将处理逻辑改为失去焦点时仍不提交数据变更，直到切换item或按下enter键才提交。
8、新增扩大选框的功能
1、PPOCRLabel now supports importing images from Chinese paths, originally importing images containing Chinese paths would cause a crash.
2、PPOCRLabel now supports moving anchor points that are covered by other boxes, originally it could not move the covered anchor points.
3、Fix the syntax error caused by mistakenly inputting characters in utility.py.
4、Repair the type error caused by inputting …
> Fixed some bugs that caused PPOCRLabel to crash, added ability to expand checkboxes

- ppocr/postprocess/picodet_postprocess.py
- tools/infer/predict_det.py
Performance optimization
Others
* Handle conflict where a box is simultaneously recognized as multiple labels.
* Split image with one side much greater than the other side recursively and process each with overlap to enhance performance.
> Optimize prediction on long image and deduplicate similar boxes with multiple lables

- PPOCRLabel/libs/shape.py
当QPointF 获取异常时，self.center  赋予默认值
Bug fixes 
Others
操作矩形绘制时，有机会导致异常退出。增加异常处理机制。
异常信息：
”PPOCRLabel\libs\shape.py", line 95, in close
self.center = QPointF((self.points[0].x() + self.points[2].x()) / 2,
IndexError: list index out of range
- [ √ ] 这个 PR 是提交到dygraph分支或者是一个cherry-pick，否则请先提交到dygarph分支。
- [ √ ] 这个PR清楚描述了功能，帮助评审能提升效率。This PR have fully described what it does such that reviewers can speedup.
- [ √ ] 这个PR已经经过本地测试。This PR can be convered by current tests or already test locally by you.
> Fix QPointF IndexError: list index out of range

- ppocr/postprocess/rec_postprocess.py
Bug fixes
Others
Fixed a bug that occurred during the rec_r45_visionlan model evaluation process.
> fix a bug for rec_postprocess.py

- ppstructure/recovery/table_process.py
fix #10649
Others
版面恢复时，对表格的html取到的列大于表格总列数的情况进行处理
> fix: layout recovery image:xxx.png,err msg: list index out of range

- ppocr/postprocess/rec_postprocess.py
paddle main code to reverse label for RTL languages has bug, try to use [python-bidi](https://pypi.org/project/python-bidi/). this works fine
> reverse output for rtl languages has bug.

- StyleText/engine/text_drawers.py
Bug fixes
Others
`getsize` is deprecated and will be removed in Pillow 10 (2023-07-01). Use `getbbox` or `getlength` instead.
```shell
cd StyleText
python tools/synth_dataset.py -c configs/dataset_config.yml
```
```
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
```
> fix AttributeError

- ppocr/utils/utility.py
- ppstructure/pdf2word/pdf2word.py
- requirements.txt
To address the compatibility issues caused by PyMuPDF dependency. 
- license compatibility: #11634, ##8873 
- env compatibility: #11119,#7934, #11662 
- and you can see more discussions by searing PyMuPDF in issues.
This pull request proposes a lazy import for PyMuPDF. This means:
- No PyMuPDF dependency: PyMuPDF will be removed from the requirements.txt file.
- Error handling: An informative error message will guide the user to install PyMuPDF if it's not already present in their environment. This error will only occur when PyMuPDF functionality is actually required.
Additionally, if this PR is accepted, the following actions will be necessary:
- Release a new version of PaddleOCR.
- Update relevant documentation within this repository.
I've used `addle.util.try_import` in the …
> lazy import PyMuPDF

- .github/workflows/python-publish.yml
- paddleocr.py
- setup.py
this is cherry-pick of recent commits: c306d288 8a99bc93 d28d9e70 89e0a15c landed in release/2.7 branch. In the future, when we create a release, we can use .github/workflows/python-publish.yml to publish package automatically to pypi. 
Some thing we can improve:
- use a pyproject.toml file in this project, which is the recommended way for python packaging, see details here: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/. By doing so, we can use `python -m build` to build and package this project, which is more modern way for python packaging.
- dynamic versioning, get version of this package by using `paddleocr.VERSION` requires complex env setup (see paddleocr.py), we may need a better mechanism for doing this. To avoid changing paddleocr.py, a trick is used in …
> setup a workflow for publishing package to pypi

- ppocr/utils/utility.py
- ppstructure/pdf2word/pdf2word.py
Bug fixes
Others
This pull request addresses the incorrect usage of the `try_import` function from `paddle.utils` in both `ppocr/utils/utility.py` and `ppstructure/pdf2word/pdf2word.py` (#11808).
此 PR 解决了 `ppocr/utils/utility.py` 与 `ppstructure/pdf2word/pdf2word.py` 中误用 `paddle.utils` 中的 `try_import` 函数的问题（#11808）。
> fix: Correct misuse of `try_import` from `paddle.utils`

- PPOCRLabel/libs/utils.py
Bug fixes
PPOCRLabel/libs/utils.py 文件中
在PPOCRLabel/libs/utils.py文件中，convert_token函数，会将HTML格式转换为标签。有如下代码：
```
if 'colspan' in col:
_, n = col.split('colspan=')
token_list.append(" colspan=\"{}\"".format(n[0]))
if 'rowspan' in col:
_, n = col.split('rowspan=')
token_list.append(" rowspan=\"{}\"".format(n[0]))
```
这里对HTML格式中跨行或者跨列单元格的格式进行format。在实际应用中，会存在一些比较极端的例子，比如某个单元格合并超过10行或者10列。因此只对n的第一位进行取值，显然不正确。如下边的例子：
因此，将代码修改为下面形式，即可解决问题，并且在实际使用中没有发现问题
```
if 'colspan' in col:
_, n = col.split('colspan=')
token_list.append(" colspan=\"{}\"".format(str(int(n))))
if 'rowspan' in col:
_, n = col.split('rowspan=')
token_list.append(" rowspan=\"{}\"".format(str(int(n))))
```
This PR is pushed to the dygraph branch or cherry-picked from the dygraph branch. Otherwise, please push your changes to the …
> Fix the error of token_list formatting only taking the first digit when the number of cells across rows or columns is greater than 10.

- doc/doc_ch/quickstart.md
fix issues:
1.getPixmap() function is not recognized,changing to get_pixmap 
2.fix TypeError when paddle recognized an empty page 
3.pre-stored pageCount to avoid issues
4.added GPU usage
getPixmap好像是个别名函数，我不知道是我配置的问题还是新版本弃用了，在我这里只有get_pixmap能用，可能要麻烦你们再测试一下
然后识别到空页会直接退出弹TypeError有点太难绷了，于是就有了这个pr（
> Update quickstart.md for a better python pdf demo

- ppstructure/predict_system.py
This PR is likely to close the following issues:
- #10270
- #10322
- #10367
- #11278
- #11665
- #11302
- #11328 
- #11869
> Enhance the OCR recognition accuracy of PPStructure.

- ppocr/modeling/backbones/rec_nrtr_mtb.py
- ppocr/modeling/backbones/rec_svtrnet.py
- ppocr/modeling/backbones/rec_vit.py
- ppocr/modeling/backbones/rec_vit_parseq.py
- ppocr/modeling/heads/rec_abinet_head.py
- ppocr/modeling/heads/rec_aster_head.py
- ppocr/modeling/heads/rec_att_head.py
- ppocr/modeling/heads/rec_cppd_head.py
- ppocr/modeling/heads/rec_multi_head.py
- ppocr/modeling/heads/rec_nrtr_head.py
- ppocr/modeling/heads/rec_sar_head.py
- ppocr/modeling/heads/rec_satrn_head.py
- ppocr/modeling/heads/rec_spin_att_head.py
- ppocr/modeling/heads/sr_rensnet_transformer.py
- ppocr/modeling/heads/table_master_head.py
- ppocr/modeling/necks/csp_pan.py
- ppocr/modeling/necks/sast_fpn.py
- ppocr/modeling/transforms/tbsrn.py
- ppocr/modeling/transforms/tps_spatial_transformer.py
paddle.shape(tensor)在最新的动转静（SOT）中，会造成子图打断，进而影响模型性能。统一改成tensor.shape。
> use tensor.shape bug not paddle.shape(tensor)

- paddleocr.py
- ppstructure/layout/predict_layout.py
发现面版识别一开onnx就出问题，看了下其他的反馈，还是修复下这个问题好点
issue tracking:
- https://github.com/PaddlePaddle/PaddleOCR/issues/8028
- **修复前**
原来情况面版分析使用Onnx第一个报错：
第二个报错
- **修复后**
> 面版识别添加onnx支持完善

- README.md
> fix wrong link for 通用OCR in README.txt

- ppocr/postprocess/db_postprocess.py
- tools/infer/predict_det.py
In case of ` det_box_type='poly'`, for some images, `np.array(offset.Execute(distance))` can result in inhomogeneous part of the detection box list, which cannot be casted into numpy array directly. Due to this the following error occurs:
```
File "C:\Users\ekser\OneDrive\Documents\OCR\cwat-integrator\venv_new\lib\site-packages\paddleocr\paddleocr.py", line 670, in ocr
dt_boxes, rec_res, _ = self.__call__(img, max_dt_boxes, cls)
File "C:\Users\ekser\OneDrive\Documents\OCR\cwat-integrator\venv_new\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 76, in __call__
dt_boxes, elapse = self.text_detector(binarize_img(img))
File "C:\Users\ekser\OneDrive\Documents\OCR\cwat-integrator\venv_new\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 318, in __call__
post_result …
```
> Error with pyclipper inhomogeneous expanded array

- configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_cml.yml
#10685
修复训练过程中找不到對應模型和训练时计算精度报错
模型名称有出入
PaddleOCR用的是PPLCNetV3而非PPLCNetNewV3
解决方案：
在Backbone下把PPLCNetNew改成PPLCNetV3，在添加一行det: true
训练时计算精度报错
发现shappe_list是一个 batch_size * 640(height) *640(width) 的数组， 显然下标访问后取值无法返回src_h, src_w, ratio_h, ratio_w
解决方案：
set: cal_metric_during_train: false可直接运行
...
> 【OCR Issue No.2】修复训练过程中找不到對應模型和训练时计算精度报错

- ppocr/utils/network.py
当配置文件中指定了 `pretrained`，每次训练时都会重复下载模型，而不是先检查是否存在此模型。
https://github.com/PaddlePaddle/PaddleOCR/blob/960243862f6c6833f58e39f3b74864cba15edfeb/configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_cml.yml#L58-L60
> fix the issue of repeatedly downloading pretrained model

- doc/doc_en/slice_en.md
- paddleocr.py
- tools/infer/predict_system.py
- tools/infer/utility.py
PaddleOCR does not work on large documents/images, this feature consists of a sliding window inference method, which although takes longer (expectedly), uses a sliding window to create slices of the input image and run detection+recognition on it.  Unlike the default code, it gives correct results. The vertical and horizontal strides are adjustable by the user.
Output on an image of dimensions (5088x3600):
Without sliding window:
With sliding window:
Note: It could use a postprocessing step where the adjacent detections are merged into one, if needed.
> added sliding window for large image inference

- benchmark/PaddleOCR_DBNet/post_processing/seg_detector_representer.py
- benchmark/PaddleOCR_DBNet/utils/ocr_metric/icdar2015/quad_metric.py
numpy升级时，np.int已经不受支持，需要将框架中使用的np.int升级为np.int8/int32/int64。
本PR清理了剩余的一些np.int。
- https://github.com/PaddlePaddle/PaddleOCR/issues/8743
- https://github.com/PaddlePaddle/PaddleOCR/issues/11906
> fix the error of `np.int`

- configs/det/det_r50_db++_icdar15.yml
- configs/det/det_r50_db++_td_tr.yml
在使用多边形box格式进行文本检测时，仅仅修改配置文件中的det_box_type为poly是不生效的，排查发现db_postprocess类中关于输出box格式的字段定义为box_type，导致config中的配置无法传递，仅使用默认quad作为box输出。
> fix_config_file_about_dbnet_poly_detection

- tools/infer/predict_det.py
I added the possibility to save the detection logs to file.
The code was almost all there already, just some arguments weren't passed the right way in order to save the detection logs to file.
In case, we could also implement this feature for the other scripts in `tools/infer/`.
> Save detection inference logs to file

- tools/infer/predict_rec.py
I added the possibility to save the recognition logs to file.
Same as #12042 but for recognition instead of detection.
If later you want to implement your own logger and move away from AutoLog (as briefly mentioned in [this comment](https://github.com/PaddlePaddle/PaddleOCR/pull/12042#discussion_r1601502917)), that's also good, but it will require more changes to the code. So, in the meanwhile, this PR quickly implements logging to file for recognition inference 😄
> Save recognition inference logs to file

- ppstructure/recovery/table_process.py
```
paddleocr --image_dir=Snipaste_2024-05-29_19-56-45.png --type=structure --recovery=True
```
- before fix:
```
[2024/05/29 19:57:16] ppocr INFO: processing 1/1 page:
[2024/05/29 19:57:17] ppocr DEBUG: dt_boxes num : 44, elapsed : 0.46419310569763184
[2024/05/29 19:57:20] ppocr DEBUG: rec_res num  : 44, elapsed : 3.558274745941162
[2024/05/29 19:57:21] ppocr DEBUG: dt_boxes num : 44, elapse : 0.4544041156768799
[2024/05/29 19:57:25] ppocr DEBUG: rec_res num  : 44, elapse : 3.340306043624878
[2024/05/29 19:57:25] ppocr ERROR: error in layout recovery image:Snipaste_2024-05-29_19-56-45, err msg: list index out of range
```
- after fix:
```
[2024/05/29 20:06:55] ppocr INFO: processing 1/1 page:
[2024/05/29 20:06:56] ppocr DEBUG: dt_boxes num : 44, elapsed : 0.46018409729003906
[2024/05/29 …
```
> fix layout recovery error: list index out of range

- paddleocr.py
```shell
paddleocr --image_dir 335849306-b6c1b619-2d1a-4932-be92-06c7bb8c044e.png --lang en --det False
```
```
[2024/06/03 09:26:41] ppocr INFO: ('(InvalidArgument) Broadcast dimension mismatch #12440', 0.9995993971824646)
Traceback (most recent call last):
File "/Users/wangxin/miniconda3/envs/ppocr/bin/paddleocr", line 8, in <module>
sys.exit(main())
File "/Users/wangxin/repos/PaddleOCR/paddleocr.py", line 898, in main
val += str(box[0]) + "," + str(box[1]) + ","
IndexError: string index out of range
```
```shell
paddleocr --image_dir 335849306-b6c1b619-2d1a-4932-be92-06c7bb8c044e.png  --det False 
```
```
[2024/06/03 09:26:48] ppocr INFO: ('(InvalidArgument) Broadcast dimension mismatch #12440', 0.9899256229400635)
Traceback (most recent call last):
File …
```
> fix wrong output when --det=False

- README.md
Paddle2ONNX 模型转化与预测 现在是连接到英文文件，改正为中文文件。
> [doc] Fix wrong link

- tools/infer/predict_rec.py
"AttributeError: module 'ntpath' has no attribute 'is_dir'. Did you mean: 'isdir'?" in python 3.10
> fix wrong function name

- ppstructure/predict_system.py
最近在使用paddleocr的版面分析功能，使用的pypi上下载的2.7.3最新版，发现PPStructure返回的result中的layout区块信息存在高iou但type不同的情况，
[示例pdf页面](https://github.com/user-attachments/files/15831530/j.reprotox.2004.06.014.pdf)
之前用过其他的版面分析模型，会在返回的layout信息中提供每个layout_block的score信息，方便在后续处理的pipeline中对高iou的区块做低score区块移除处理。
看了最新的仓库代码（2.8.0版本），发现相较于2.7.3whl版本，PaddleOCR/ppocr/postprocess/picodet_postprocess.py
中已增加了layout的score返回，但是在PaddleOCR/ppstructure/predict_system.py 中，没有增加对应的返回参数
现已补全result中的layout score参数，便于后续pipeline的开发使用
> add layout score return

- ppstructure/recovery/requirements.txt
There are 1 security vulnerabilities found in fonttools 4.24.0
- [CVE-2023-45139](https://www.oscs1024.com/hd/CVE-2023-45139)
Upgrade fonttools from 4.24.0 to 4.43.0 for vulnerability fix
Ideally, no insecure libs should be used.
By using the [GitHub Actions](https://github.com/murphysecurity/actions) configurations provided by murphysec, we can conduct automatic code security checks in our CI pipeline.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
> fix(sec): upgrade fonttools to 4.43.0

- ppstructure/table/matcher.py
> fix: table recognition content is not escaped properly

- ppstructure/predict_system.py
```Python
from paddleocr import PPStructure
table_ocr = PPStructure(
use_pdserving=False, use_gpu=False, lang="en", layout=False, show_log=False
)
result = table_ocr(
"./data/paddle.png", return_ocr_result_in_table=True
)
```
```
File "/Users/wangxin/repos/PaddleOCR/paddleocr.py", line 855, in __call__
res, _ = super().__call__(img, return_ocr_result_in_table, img_idx=img_idx)
File "/Users/wangxin/repos/PaddleOCR/ppstructure/predict_system.py", line 172, in __call__
"score": region["score"],
KeyError: 'score'
```
- #13068
> fix bug when layout_predictor is None

- tools/program.py
refering to-https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/incubate/ModelAverage_en.html
it should be paddle.incubate.ModelAverage and not paddle.incubate.optimizer.ModelAverage
> line 445 program.py

- doc/doc_ch/detection.md
add amp train notes for detection model, details see https://github.com/PaddlePaddle/PaddleOCR/discussions/12445
> [doc]add amp train notes for detection train

- deploy/cpp_infer/src/ocr_cls.cpp
- deploy/cpp_infer/src/ocr_det.cpp
- deploy/cpp_infer/src/ocr_rec.cpp
- deploy/cpp_infer/src/structure_layout.cpp
- deploy/cpp_infer/src/structure_table.cpp
When using the --enable_mkldnn command line option, MKLDNN should be enabled when set to true and disabled when set to false. But, using the PaddlePaddle v3.0.0-beta1 inference library, the --enable_mkldnn=false option did not work as expected, causing MKLDNN to remain enabled regardless of the setting.
﻿
This commit adds a call to `config.DisableMKLDNN()` in the else branch to explicitly disable MKLDNN when `--enable_mkldnn=false` is set.
---
正常情况下，命令行指令 `--enable_mkldnn=false` 会关闭mkl加速。
使用旧版推理库（PaddlePaddle v2.3.2）时，如果不执行 `config.EnableMKLDNN();` ，那么mkl默认是关闭的，指令没问题。
但是，使用新版推理库（PaddlePaddle v3.0.0-beta1）时，就算不执行 `config.EnableMKLDNN();` ，mkl也是默认开启的。
这就导致 `--enable_mkldnn=false` 指令失效了。无论设置什么，mkl都是开启状态。
此PR增加了显式调用 `config.DisableMKLDNN()` 的代码，使得 `--enable_mkldnn=false` 时，可以正确地关闭mkl加速。
测试环境： …
> Fix cpp_infer "--enable_mkldnn=false" not effective

- README.md
- README_en.md
- docs/quick_start.en.md
- docs/quick_start.md
- docs/update.en.md
- docs/update.md
- mkdocs.yml
> docs: Update README

- docs/ppstructure/model_train/recovery_to_doc.en.md
- docs/ppstructure/model_train/recovery_to_doc.md
- docs/ppstructure/quick_start.en.md
- docs/ppstructure/quick_start.md
- ppstructure/docs/quickstart.md
- ppstructure/docs/quickstart_en.md
- ppstructure/recovery/README.md
- ppstructure/recovery/README_ch.md
Document path adjustment, update the path in the demonstration，from [issue](https://github.com/PaddlePaddle/PaddleOCR/issues/13538)
> docs: Update the pdf file path in the operation demonstration

- configs/rec/rec_latex_ocr.yml
- docs/algorithm/formula_recognition/algorithm_rec_latex_ocr.en.md
- docs/algorithm/formula_recognition/algorithm_rec_latex_ocr.md
- ppocr/data/latexocr_dataset.py
- ppocr/utils/formula_utils/math_txt2pkl.py
1. 将生成数据集中的绝对路径修改为相对路径，从而支持PaddleX的CI。
> 修改LaTeXOCR的数据处理部分，将生成的数据集中的绝对路径改为相对路径

- deploy/cpp_infer/CMakeLists.txt
[windows推理库(3.0.0-beta1 版本)-MKL](https://www.paddlepaddle.org.cn/inference/master/guides/install/download_lib.html#windows)将mkldnn文件夹改名为onednn
> fixed: mkldnn -> onednn

- paddleocr.py
* add layout score return
* fix(paddleocr): correct import path for predict_system
to fix ModuleNotFoundError: No module named 'tools.infer'
* fix(paddleocr): move from tools.infer import predict_system under "tools" define to slove ModuleNotFoundError: No module named 'tools.infer'
Close #13769
> [cherry-pick] Solve ModuleNotFoundError: No module named 'tools.infer'

- tools/infer/utility.py
Close #12043
Previously inference using the SRN algorithm would report an error, `W0910 03:27:08.048635  9645 gpu_cpu_map_matmul_to_mul_pass.cc:425] matmul op not support broadcast, please check inputs'shape. `. So we may need to remove the pass `gpu_cpu_map_matmul_to_mul_pass`.
```shell
python3 tools/infer/predict_rec.py --image_dir="./doc/imgs_words/en/word_1.png" --rec_model_dir="./inference/rec_srn/" --rec_image_shape="1,64,256"  --rec_algorithm="SRN" --rec_char_dict_path=./ppocr/utils/ic15_dict.txt  --use_space_char=False
```
```text
[2024/09/10 03:27:06] ppocr WARNING: The first GPU is used for inference by default, GPU ID: 0
[1m[35m--- Running analysis [ir_graph_build_pass][0m
I0910 03:27:06.930096  9645 executor.cc:183] Old Executor is Running.
[1m[35m--- Running analysis …
```
> fix SRN algorithm infer error

- ppstructure/predict_system.py
- ppstructure/recovery/recovery_to_doc.py
- ppstructure/recovery/recovery_to_markdown.py
- ppstructure/utility.py
**前言**
尊敬的 ppocr 官方人员您好，我是一名 ppocr 项目的使用者，在日常工作学习中我都会用到ppocr，我深感 ppocr 的强大之处！同时能为 ppocr 做贡献也是我非常想要做的事情。非常期待您在百忙之中看看我写的代码是否是 ppocr 所需要的。
**改动如下：**
1. 在  `ppstructure`  管道中添加  `latex_ocr`  公式识别功能；
a. 修改 `ppstructure/predict_system.py` 文件中 `StructureSystem` 类，添加 `latex_ocr` 模型和布局为公式的区域处理；
b. 由于 docx 中不支持插入 latex 公式，在 `ppstructure/recovery/recovery_to_doc.py` 文件中 `convert_info_docx` 函数中跳过latex公式；
c. 在 `ppstructure/utility.py` 中 `draw_structure_result` 函数中可视化 ocr 结果中跳过 latex 公式；
2. 添加 pdf 转 markdown 文件功能
a. 在目录 `ppstructure/recovery` 下添加文件 `recovery_to_markdown.py`，其中程序功能为转换ppstructure识别结果为markdown文件。其中对于文本区域处理目前给出了两种处理方法，第一种为每一个自然段分割标志位开头两个空格,第二种为每个自然段开头没有空格，这种情况下以每个自然段最后一行一般不会是“满行”，而是会留有空余空间；
b. `ppstructure/predict_system.py` 文件中调用转换 ppstructure 识别结果到 markdown 文件的函数；
3. 添加必要的命令行参数选项；
a. 添加 …
> 1.在ppstructure管道中添加latex_ocr公式识别功能；2.添加pdf转markdown文件功能

- docs/ppstructure/quick_start.en.md
- docs/ppstructure/quick_start.md
- paddleocr.py
- ppstructure/docs/quickstart.md
- ppstructure/docs/quickstart_en.md
paddleocr.py文件中class PPStructure适配了上个pr添加的公式识别；
paddleocr.py文件中添加了pdf转换为markdown文件的支持，方便命令行快速开始。
文档修改如下四个文件:
ppstructure
PaddleOCR/ppstructure/docs/quickstart.md
PaddleOCR/ppstructure/docs/quickstart_en.md
docs
PaddleOCR/docs/ppstructure/quick_start.md
PaddleOCR/docs/ppstructure/quick_start.en.md
在以上四个文档中添加了pdf转换为markdown文件的快速开始，和必要的参数说明。
> pdf to markdown document

- .github/workflows/build_publish_develop_docs.yml
This pull request includes a small change to the `.github/workflows/build_publish_develop_docs.yml` file. The change ensures that the latest `gh-pages` branch is fetched before deploying and setting the default documentation version.
* [`.github/workflows/build_publish_develop_docs.yml`](diffhunk://#diff-b6f5f260b0b6ea639f348696541c0db1f0ddddeb64e6419fdfa682440ad63340R30): Added a command to fetch the `gh-pages` branch with a depth of 1 before deploying and setting the default version using `mike`.
> ci: Fix mike error

- README.md
The former link in README.md for quick start is broken. I added _latest_ between PaddleOCR/ and quick_start.html to make the link work.
> Update README.md, fixed broken quick start link

- tools/program.py
fix https://github.com/PaddlePaddle/PaddleOCR/issues/13985 by adding a simple guard.
> avoid ZeroDivisionError when training.

- tools/infer/utility.py
In current live version `PaddleOCR` with `use_onnx` flag works only either with `CPUExecutionProvider` or with `CUDAExecutionProvider` is available and `use_gpu` flag is provided.
Onnx ecosystem have lots of different execution providers and I see no reason to limit it only to proprietary Nvidia tech stack. Here is a list of currently available execution providers: https://onnxruntime.ai/docs/execution-providers/
This PR adds a new `onnx_providers` array args that is being used in `create_predictor` function when it is passed to initiate onnx runtime `InferenceSession` with requested execution providers.
> Allow `create_predictor` function to accept array of ONNX Execution Providers

- .github/workflows/close_inactive_issues.yaml
This pull request involves removing the `inactivity-lock` job from the GitHub Actions workflow configuration file. This change simplifies the workflow by eliminating the step that locks inactive issues and pull requests.
Changes in `.github/workflows/close_inactive_issues.yaml`:
* Removed the `inactivity-lock` job, which included steps to lock closed issues and PRs after a period of inactivity.
> remove lock inactive issues

- ppocr/data/imaug/operators.py
- ppocr/data/imaug/randaugment.py
- ppocr/data/imaug/table_ops.py
- ppocr/data/lmdb_dataset.py
- ppocr/utils/save_load.py
- pyproject.toml
- requirements.txt
- test_tipc/supplementary/data.py
- test_tipc/supplementary/utils.py
https://pypi.org/project/six is no longer needed.
https://github.com/PaddlePaddle/PaddleOCR/blob/9308d5e7884e322008b2cd5ee7e23e02a254a1ac/pyproject.toml#L17
> Remove Python 2 compatibility dependency six

- ppocr/data/imaug/iaa_augment.py
- tests/test_iaa_augment.py
This pull request includes changes to the `ppocr` data augmentation and its corresponding tests to update the data type of `polys` from a list to a numpy array. This ensures consistency and compatibility with other numpy operations.
Changes to `ppocr` data augmentation:
* [`ppocr/data/imaug/iaa_augment.py`](diffhunk://#diff-cfb976e0fb8bb05e4bca0b6b32b49a42f55d1ff7266ec93d6bac9baabfa2716dL211-R211): Modified the `__call__` method to set `data["polys"]` as a numpy array instead of a list.
Updates to tests:
* [`tests/test_iaa_augment.py`](diffhunk://#diff-997848a3b11501077cb5fd1cdedab72dd24a33b98431fd14fb1e56e0b0902ab3L53-R55): Updated the test `test_iaa_augment_default` to check that `transformed_data["polys"]` is a numpy array instead of a list.
Fixes:
- …
> fix benchmark det_r50_vd_pse_v2_0 train error

- tools/infer/utility.py
This pull request includes changes to the `create_predictor` function in `tools/infer/utility.py` to improve the logic for locating model files. The most important changes include simplifying the file existence checks and enhancing error messages for missing files.
Improvements to file existence checks:
* Simplified the logic by removing redundant checks for `model.pdmodel` and `inference.pdmodel` files and instead using formatted strings for file paths.
* Enhanced the error messages to provide clearer information when neither `.pdmodel` nor `.json` files are found.
Enhancements to error handling:
* Updated the error message to specify which `.pdiparams` file is missing when it is not found in the specified directory.
* Added a conditional to set the `model_file_path` based on the …
> update infer/utility.py to support json format model

- tools/infer/utility.py
- tools/program.py
> Support inference for GCU

- ppstructure/recovery/recovery_to_markdown.py
when I run the quicktour code as following:
```python
import os
import cv2
from PIL import Image
from pathlib import Path
from paddleocr import PPStructure,save_structure_res, draw_structure_result
from paddleocr.ppstructure.recovery.recovery_to_doc import sorted_layout_boxes
from paddleocr.ppstructure.recovery.recovery_to_markdown import convert_info_markdown
table_engine = PPStructure(recovery=True, lang='en')
save_folder = './paddleocr_markdown_restore_new'
img_path = './pics/20241113-091849.jpeg'
img = cv2.imread(img_path)
result = table_engine(img)
save_structure_res(result, save_folder, os.path.basename(img_path).split('.')[0])
for line in result:
print(line)
im_show = draw_structure_result(img, result, font_path='/cpfs/data/user/zhiqi/mm_ocr/got/fonts/simfang.ttf')
im_show = …
```
> fix: Title text partially missing issue in `recovery_to_markdown.py`

- docs/ppocr/model_train/recognition.en.md
- docs/ppocr/model_train/recognition.md
- docs/ppstructure/quick_start.en.md
- docs/ppstructure/quick_start.md
This pull request includes significant updates to the `docs/ppocr/model_train/recognition.en.md` and `docs/ppstructure/quick_start.en.md` files to improve the documentation for PaddleOCR. The changes provide clearer instructions for data preparation, training, evaluation, and model inference. Additionally, there are updates to the installation instructions for PaddlePaddle with different CUDA versions.
Documentation Improvements:
* [`docs/ppocr/model_train/recognition.en.md`](diffhunk://#diff-8db1254a8a85f63a7819d54673b81a4e31416613afec443818f912cb4e34b115R8-R90): Added comprehensive instructions for data preparation, including dataset formats, symbolic links, and custom datasets.
* [`docs/ppocr/model_train/recognition.en.md`](diffhunk://#diff-8db1254a8a85f63a7819d54673b81a4e31416613afec44 …
> docs: update quick_start and recognition doc

- ppstructure/recovery/recovery_to_doc.py
- ppstructure/recovery/recovery_to_markdown.py
This pull request includes changes to improve the handling of empty regions in the `ppstructure` module. The changes ensure that regions of type "figure" are not skipped even if they have no content.
Improvements to handling empty regions:
* [`ppstructure/recovery/recovery_to_doc.py`](diffhunk://#diff-40d793b87ea5ce6dc31541b8a73dc004a5a2d9df3438bf717e9773c36b025cd3L40-R40): Modified the condition in `convert_info_docx` to continue only if the region is empty and its type is not "figure".
* [`ppstructure/recovery/recovery_to_markdown.py`](diffhunk://#diff-d4707d5b26d28fef1614cdc7e2d05fe7a096bd71c9acaeaff4510b8413290fceL150-R150): Modified the condition in `convert_info_markdown` to continue only if the region is empty and its type is not "figure".
close #14292
> fix: unable to export images without text to docx format

- ppocr/modeling/heads/rec_sar_head.py
Others 
Others 
https://github.com/PaddlePaddle/Paddle/pull/69589 后 paddle.shape返回int64类型。属于Paddle的不兼容升级。需要在套件中适配。
> paddle.shape return int64 tensor

- ppocr/modeling/heads/rec_sar_head.py
https://github.com/PaddlePaddle/PaddleOCR/pull/14318
对shape64的改法是将paddle.shape的结果cast成int32。
更好的改法应该是，对使用paddle.shape的地方进行适配。
本PR进行修复。
> fix shape64

- paddleocr.py
修复使用自定义模型的时候，无法自定义`rec_image_shape`的问题
> fix: replace `rec_image_shape` when manually set

- docs/ppocr/blog/multi_languages.en.md
- docs/ppocr/blog/multi_languages.md
I think I found a mistake in your documentation regarding the supported languages.
You are stating that you support the language "Saudi Arabia" with the language code "sa".
I think you mean "Sanskrit" in this case.
When looking at the PaddleOCR.py file, "sa" is also sorted in the devanagari list, which supports my assumption. And "Saudi Arabia" is also not a language at all.
While I was at it I also corrected a few spelling mistakes I noticed.
> Fix language error and spelling mistakes in the documentation

- test_tipc/supplementary/train.py
- tools/eval.py
- tools/train.py
移除FLAGS_max_inplace_grad_add的配置，这个max inplace grad add当前基于inplace的逻辑实现的，cinn不容易处理（开启编译器之后，部分任务性能会差距10%），暂时移除该配置，该配置仅影响动转静之后的性能
> remove max inplace grad

- deploy/cpp_infer/include/clipper.h
- deploy/cpp_infer/include/ocr_cls.h
- deploy/cpp_infer/include/ocr_det.h
- deploy/cpp_infer/include/ocr_rec.h
- deploy/cpp_infer/include/paddleocr.h
- deploy/cpp_infer/include/paddlestructure.h
- deploy/cpp_infer/include/postprocess_op.h
- deploy/cpp_infer/include/preprocess_op.h
- deploy/cpp_infer/include/structure_layout.h
- deploy/cpp_infer/include/structure_table.h
- deploy/cpp_infer/include/utility.h
- deploy/cpp_infer/src/clipper.cpp
- deploy/cpp_infer/src/ocr_cls.cpp
- deploy/cpp_infer/src/ocr_det.cpp
- deploy/cpp_infer/src/ocr_rec.cpp
- deploy/cpp_infer/src/paddleocr.cpp
- deploy/cpp_infer/src/paddlestructure.cpp
- deploy/cpp_infer/src/postprocess_op.cpp
- deploy/cpp_infer/src/preprocess_op.cpp
- deploy/cpp_infer/src/structure_layout.cpp
- deploy/cpp_infer/src/structure_table.cpp
- deploy/cpp_infer/src/utility.cpp
When exception caught in ClipperLib::ClipperOffset::Execute, just printf the what message to stderr and return false. When DBPostProcessor::UnClip failed in calling ClipperLib::ClipperOffset::Execute, just return (empty or null) cv::RotatedRect().
> CPP: Make functions mostly noexcept to improve runtime performance

- deploy/cpp_infer/docs/windows_vs2019_build.md
- deploy/cpp_infer/docs/windows_vs2022_build.md
- deploy/cpp_infer/readme.md
Hi!
Last week I wanted to try out the C++ inference version of PaddleOCR and noticed that the compilation guide for windows only existed in chinese and it was also quite outdated aswell.
So after I got it working and compiled paddleocr successfully on windows I took the time to write an english cmake compilation guide and updated it with my recent findings.
I've also changed the link in the cpp infer readme to link now to the english version that I created because it itself was written in english. On top of the readme of both CMAKE compilation guides I added buttons to switch between the languages.
I hope you like it!
> Add english docu for CMAKE compilation on windows

- ppocr/utils/network.py
Sorry for the second PR on this topic, I noticed afterward that another path (`MODELS_DIR`) was also hardcoded for downloading models. It will now use the environment variable  `PADDLE_OCR_BASE_DIR` if this one exists.
> use the env variable PADDLE_OCR_BASE_DIR if it exists to download models

- docs/quick_start.en.md
- docs/quick_start.md
This pull request includes updates to the documentation files to enhance clarity and provide additional information about the OCR model storage location and usage instructions.
Documentation improvements:
* [`docs/quick_start.en.md`](diffhunk://#diff-f58e63a359fbb494c2bec6911b2110f031ff8f30a0a4f19f703e35ed6ce7054bL27-R28): Added a note to clarify how to customize the storage location for OCR models by setting the `PADDLE_OCR_BASE_DIR` environment variable.
* [`docs/quick_start.md`](diffhunk://#diff-61f4196322cfa9f52c5f548f13b7f781243b2cae898862a8688462d914ba7173R34-R38): Added a note in Chinese to explain how to customize the storage location for OCR models by setting the `PADDLE_OCR_BASE_DIR` environment variable, including the default storage paths for Linux/macOS and Windows.
* …
> docs: update quick_start doc

- docs/infer_deploy/android_demo.en.md
- docs/infer_deploy/android_demo.md
This pull request includes significant updates to the documentation for the Android Demo of PaddleOCR. The changes enhance the clarity and usability of the instructions for setting up and running the demo, as well as providing detailed descriptions of the supported operation modes and settings.
Documentation Updates:
* [`docs/infer_deploy/android_demo.en.md`](diffhunk://#diff-c92db19fe62d6f2951ef0be738c1f7ce29acab1619b35da7b65796538dc4e66eR1-R114): Added a comprehensive guide for the Android Demo, including sections on the introduction, recent updates, environment setup, project import, running the demo, operation modes, and settings.
* [`docs/infer_deploy/android_demo.md`](diffhunk://#diff-455eea8074c7f6f8a074cee2ee5cdb0cd67f1a3b1c722959b7a1051254e2c19aL12-R12): Updated the introduction …
> docs: update android demo doc

- ppocr/data/imaug/iaa_augment.py
- pyproject.toml
- requirements.txt
This pull request includes updates to handle compatibility with different versions of the `albumentations` library and simplifies the dependency management in `pyproject.toml`.
* [`ppocr/data/imaug/iaa_augment.py`](diffhunk://#diff-cfb976e0fb8bb05e4bca0b6b32b49a42f55d1ff7266ec93d6bac9baabfa2716dR27-R36): Introduced version checking for `albumentations` and adjusted the `ImgaugLikeResize` class to handle different versions. [[1]](diffhunk://#diff-cfb976e0fb8bb05e4bca0b6b32b49a42f55d1ff7266ec93d6bac9baabfa2716dR27-R36) [[2]](diffhunk://#diff-cfb976e0fb8bb05e4bca0b6b32b49a42f55d1ff7266ec93d6bac9baabfa2716dL44-R49)
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L59-R61): Updated the `albumentations` and `albucore` dependencies to be …
> unlock albumentations version

- tools/infer/utility.py
This pull request includes an important change to the `tools/infer/utility.py` file, specifically in the `text_visual` method. The change modifies the data type used to create a blank image, ensuring compatibility and correctness in image processing.
* [`tools/infer/utility.py`](diffhunk://#diff-c44b96eb71070ae776b3d092254a8ee3298eef0bdda6e9a68b001040524cd367L624-R624): Changed the data type from `np.int8` to `np.uint8` in the `create_blank_img` function to correctly handle image data.
* `np.int8` is a signed 8-bit integer, meaning it can store values from -128 to 127.
* The value 255 exceeds the maximum limit of 127 for `np.int8`, causing an overflow. When NumPy tries to compute 1 * 255 and store the result (255) in an int8 array, it raises the OverflowError because 255 is out of bounds.
> fix `OverflowError` in text_visual func

- ppocr/modeling/heads/rec_latexocr_head.py
remove usused mem in latex_ocr head for npu adaptation
> remove usused mem in latex_ocr head

- deploy/android_demo/app/src/main/cpp/ocr_clipper.cpp
- deploy/android_demo/app/src/main/cpp/ocr_clipper.hpp
- deploy/android_demo/app/src/main/cpp/ocr_ppredictor.h
- deploy/cpp_infer/include/clipper.h
- deploy/cpp_infer/src/clipper.cpp
- deploy/pdserving/ocr_reader.py
- deploy/pdserving/win/ocr_reader.py
- docs/update.en.md
- ppocr/data/imaug/copy_paste.py
- ppocr/data/imaug/label_ops.py
- ppocr/data/lmdb_dataset.py
- ppocr/data/pgnet_dataset.py
- ppocr/data/pubtab_dataset.py
- ppocr/data/simple_dataset.py
- ppocr/modeling/backbones/rec_micronet.py
- ppocr/postprocess/rec_postprocess.py
- ppstructure/kie/how_to_do_kie_en.md
- ppstructure/recovery/README.md
> Fix typos in several files

- README.md
- README_en.md
- docs/update.en.md
- docs/update.md
The last commit that described the newly added capabilities listed the previous year. ;-)
I've updated this to 2025.
> Fix wrong date in newly added capabilities

- docs/ppocr/blog/multi_languages.en.md
- docs/ppocr/blog/multi_languages.md
I noticed that not all supported languages are listed in the table for supported languages and abbreviations. I compared them against the one listed in the `paddleocr.py` file and added the missing ones to the table.
Now the table should be complete! :-)
> Add missing languages to documentation

- docs/paddlex/quick_start.en.md
This should fix the display of the list.
Currently, it looks like this:
Should look like this:
Thanks! 🚀
> docs: Fix formatting of a Markdown List

- README_en.md
I found a dead link in the Readme on the start page of the repository.
I updated it with the correct link.
> Fix dead link for diving into OCR

- paddleocr/_cli.py
```bash
paddleocr
```
```
usage: paddleocr [-h] [-v]
{doc_preprocessor,doc_understanding,formula_recognition_pipeline,ocr,pp_chatocrv4_doc,pp_structurev3,seal_recognition,table_recognition_v2,doc_img_orientation_classification,doc_vlm,formula_recognition,layout_detection,seal_text_detection,table_cells_detection,table_classification,table_structure_recognition,text_detection,text_image_unwarping,text_line_orientation_classification,text_recognition,install_hpi_deps}
...
```
> [Fix] Set subcommand as required

- paddleocr/_pipelines/ocr.py
If there is no model specified we now select the best available model for the specified language instead of defaulting to PP-OCRv5 which results in a not very user friendly experience.
Fixes #15642
> Enhance OCR model selection logic

- ppocr/utils/save_load.py
The bug was introduced in commit e3145103 ("import encryption for aistudio & fix sync bn"), where the following snippet:
```
try:
import encryption  # Attempt to import the encryption module for AIStudio's encryption model
encrypted = encryption.is_encryption_needed()
except ImportError:
get_logger().warning("Skipping import of the encryption module.")
encrypted = False  # Encryption is not needed if the module cannot be imported
```
caused `get_logger()` to be called too early, initializing the logger before the training arguments were passed. As a result, the training process skipped proper log redirection, and `train.log` was not created.
This patch replaces the warning with a simple `print()` statement, ensuring the logger is only initialized after training args are passed.
Fixes …
> fix train.log output (#14846)

- .github/workflows/link-check.yml
- .lycheeignore
添加自动检测项目下死链的CI
添加之后，会定期扫描仓库下所有url，给出哪些不可用来，便于针对性修复。类似：[link](https://github.com/RapidAI/RapidOCRDocs/issues/11)
> feat: add lychee for checking broken url
